import { TypeCompte } from '@prisma/client';

export const PLAN_COMPTABLE_SYCEBNL: {
  numero: string;
  nom: string;
  classe: TypeCompte;
  sens: 'DEBITEUR' | 'CREDITEUR';
  parent: string | null;
}[] = [
  { numero: '10', nom: 'Fonds associatifs', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '101', nom: 'Fonds associatifs sans droit de reprise', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '10' },
  { numero: '102', nom: 'Fonds associatifs avec droit de reprise', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '10' },
  { numero: '103', nom: 'Dotations reçues', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '10' },
  { numero: '104', nom: 'Apports en nature', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '10' },
  { numero: '11', nom: 'Réserves', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '110', nom: 'Réserves légales', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '11' },
  { numero: '111', nom: 'Réserves statutaires', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '11' },
  { numero: '118', nom: 'Autres réserves', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '11' },
  { numero: '12', nom: 'Report à nouveau', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '120', nom: 'Report à nouveau créditeur', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '12' },
  { numero: '129', nom: 'Report à nouveau débiteur', classe: TypeCompte.CLASSE_1, sens: 'DEBITEUR', parent: '12' },
  { numero: '13', nom: "Résultat de l'exercice", classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '130', nom: 'Résultat excédentaire', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '13' },
  { numero: '139', nom: 'Résultat déficitaire', classe: TypeCompte.CLASSE_1, sens: 'DEBITEUR', parent: '13' },
  { numero: '14', nom: "Subventions d'investissement reçues", classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '141', nom: "Subventions d'équipement", classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '14' },
  { numero: '142', nom: 'Subventions pour autres investissements', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '14' },
  { numero: '15', nom: 'Provisions réglementées', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '16', nom: 'Emprunts et dettes assimilées', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '161', nom: 'Emprunts obligataires', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '16' },
  { numero: '162', nom: 'Emprunts auprès des établissements de crédit', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '16' },
  { numero: '168', nom: 'Autres emprunts et dettes assimilées', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: '16' },
  { numero: '17', nom: 'Dettes de financement à long terme', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '18', nom: 'Dettes liées à des participations', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },
  { numero: '19', nom: 'Provisions financières pour risques et charges', classe: TypeCompte.CLASSE_1, sens: 'CREDITEUR', parent: null },

  { numero: '20', nom: 'Immobilisations incorporelles', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '201', nom: "Frais de recherche et de développement", classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '20' },
  { numero: '202', nom: 'Brevets, licences, logiciels', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '20' },
  { numero: '203', nom: "Fonds commercial", classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '20' },
  { numero: '21', nom: 'Immobilisations corporelles', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '22', nom: 'Terrains', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '221', nom: 'Terrains nus', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '22' },
  { numero: '222', nom: 'Terrains bâtis', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '22' },
  { numero: '23', nom: 'Bâtiments', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '231', nom: 'Bâtiments sur terrains propres', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '23' },
  { numero: '232', nom: 'Bâtiments sur terrains en location', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '23' },
  { numero: '24', nom: 'Matériel', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '241', nom: 'Matériel et outillage', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '24' },
  { numero: '244', nom: 'Matériel de transport', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '24' },
  { numero: '245', nom: 'Matériel informatique', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '24' },
  { numero: '246', nom: 'Mobilier de bureau', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '24' },
  { numero: '247', nom: 'Matériel médical et de soins', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: '24' },
  { numero: '25', nom: 'Avances et acomptes sur immobilisations', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '27', nom: 'Autres immobilisations financières', classe: TypeCompte.CLASSE_2, sens: 'DEBITEUR', parent: null },
  { numero: '28', nom: 'Amortissements des immobilisations', classe: TypeCompte.CLASSE_2, sens: 'CREDITEUR', parent: null },
  { numero: '280', nom: 'Amortissements des immobilisations incorporelles', classe: TypeCompte.CLASSE_2, sens: 'CREDITEUR', parent: '28' },
  { numero: '281', nom: 'Amortissements des immobilisations corporelles', classe: TypeCompte.CLASSE_2, sens: 'CREDITEUR', parent: '28' },
  { numero: '283', nom: 'Amortissements des bâtiments', classe: TypeCompte.CLASSE_2, sens: 'CREDITEUR', parent: '28' },
  { numero: '284', nom: 'Amortissements du matériel', classe: TypeCompte.CLASSE_2, sens: 'CREDITEUR', parent: '28' },
  { numero: '29', nom: 'Provisions pour dépréciation des immobilisations', classe: TypeCompte.CLASSE_2, sens: 'CREDITEUR', parent: null },

  { numero: '31', nom: 'Marchandises', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: null },
  { numero: '32', nom: 'Matières premières et fournitures', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: null },
  { numero: '321', nom: 'Matières premières', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: '32' },
  { numero: '322', nom: 'Fournitures de bureau et consommables', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: '32' },
  { numero: '35', nom: 'Stocks de médicaments et fournitures médicales', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: null },
  { numero: '36', nom: 'Stocks de vivres et denrées alimentaires', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: null },
  { numero: '37', nom: 'Stocks de matériaux de construction', classe: TypeCompte.CLASSE_3, sens: 'DEBITEUR', parent: null },
  { numero: '39', nom: 'Provisions pour dépréciation des stocks', classe: TypeCompte.CLASSE_3, sens: 'CREDITEUR', parent: null },

  { numero: '40', nom: 'Fournisseurs et comptes rattachés', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: null },
  { numero: '401', nom: 'Fournisseurs', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '40' },
  { numero: '408', nom: 'Fournisseurs — factures non parvenues', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '40' },
  { numero: '409', nom: 'Fournisseurs débiteurs — avances et acomptes', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: '40' },
  { numero: '41', nom: 'Membres et organismes affiliés', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: null },
  { numero: '411', nom: 'Cotisations à recevoir', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: '41' },
  { numero: '412', nom: 'Créances sur membres', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: '41' },
  { numero: '42', nom: 'Personnel', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: null },
  { numero: '421', nom: 'Personnel — rémunérations dues', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '42' },
  { numero: '422', nom: 'Personnel — avances et acomptes', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: '42' },
  { numero: '428', nom: 'Personnel — charges à payer', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '42' },
  { numero: '43', nom: 'Organismes sociaux', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: null },
  { numero: '431', nom: 'Sécurité sociale', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '43' },
  { numero: '437', nom: 'Autres organismes sociaux', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '43' },
  { numero: '44', nom: 'État et collectivités publiques', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: null },
  { numero: '441', nom: 'État — impôts et taxes', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '44' },
  { numero: '443', nom: 'État — TVA', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '44' },
  { numero: '45', nom: 'Bailleurs de fonds', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: null },
  { numero: '451', nom: "Subventions reçues d'avance", classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '45' },
  { numero: '452', nom: 'Subventions acquises', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '45' },
  { numero: '453', nom: 'Fonds reçus à justifier', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '45' },
  { numero: '46', nom: 'Débiteurs et créditeurs divers', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: null },
  { numero: '461', nom: 'Débiteurs divers', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: '46' },
  { numero: '462', nom: 'Créditeurs divers', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '46' },
  { numero: '47', nom: "Comptes transitoires ou d'attente", classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: null },
  { numero: '471', nom: 'Dépenses à classer', classe: TypeCompte.CLASSE_4, sens: 'DEBITEUR', parent: '47' },
  { numero: '472', nom: 'Recettes à classer', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: '47' },
  { numero: '49', nom: 'Provisions pour dépréciation des comptes de tiers', classe: TypeCompte.CLASSE_4, sens: 'CREDITEUR', parent: null },

  { numero: '50', nom: 'Titres de placement', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: null },
  { numero: '51', nom: 'Banques, établissements financiers', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: null },
  { numero: '511', nom: 'Chèques à encaisser', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '51' },
  { numero: '512', nom: 'Banques comptes courants', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '51' },
  { numero: '514', nom: 'Chèques postaux', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '51' },
  { numero: '515', nom: 'Mobile money et transferts électroniques', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '51' },
  { numero: '52', nom: 'Banques, crédits de décaissement', classe: TypeCompte.CLASSE_5, sens: 'CREDITEUR', parent: null },
  { numero: '57', nom: 'Caisse', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: null },
  { numero: '570', nom: 'Caisse siège', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '57' },
  { numero: '571', nom: 'Caisses terrain', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '57' },
  { numero: '58', nom: "Régies d'avances et accréditifs", classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: null },
  { numero: '581', nom: 'Régies et avances de déplacement', classe: TypeCompte.CLASSE_5, sens: 'DEBITEUR', parent: '58' },
  { numero: '59', nom: 'Provisions pour dépréciation des comptes de trésorerie', classe: TypeCompte.CLASSE_5, sens: 'CREDITEUR', parent: null },

  { numero: '60', nom: 'Achats et variations de stocks', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '601', nom: 'Achats de marchandises', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '60' },
  { numero: '602', nom: 'Achats de matières premières et fournitures', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '60' },
  { numero: '604', nom: 'Achats de médicaments et fournitures médicales', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '60' },
  { numero: '605', nom: 'Achats de vivres et denrées alimentaires', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '60' },
  { numero: '61', nom: 'Transports', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '611', nom: 'Transports sur achats', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '61' },
  { numero: '612', nom: 'Transports sur ventes', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '61' },
  { numero: '618', nom: 'Autres frais de transport', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '61' },
  { numero: '62', nom: 'Services extérieurs A', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '621', nom: 'Loyers et charges locatives', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '62' },
  { numero: '622', nom: 'Redevances de crédit-bail', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '62' },
  { numero: '623', nom: 'Entretien, réparations et maintenance', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '62' },
  { numero: '624', nom: 'Primes et cotisations assurances', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '62' },
  { numero: '63', nom: 'Services extérieurs B', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '631', nom: 'Frais de publicité et communication', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '632', nom: 'Frais de mission et déplacements', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '633', nom: 'Frais de réception', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '634', nom: 'Frais de formation', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '635', nom: 'Frais de documentation et abonnements', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '637', nom: 'Honoraires et conseils externes', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '638', nom: 'Frais de télécommunications', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '63' },
  { numero: '64', nom: 'Impôts et taxes', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '641', nom: 'Impôts et taxes récupérables', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '64' },
  { numero: '645', nom: 'Taxes sur les salaires', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '64' },
  { numero: '648', nom: 'Autres impôts et taxes', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '64' },
  { numero: '65', nom: 'Autres charges', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '651', nom: 'Pertes sur créances irrécouvrables', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '65' },
  { numero: '658', nom: 'Charges diverses de gestion', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '65' },
  { numero: '66', nom: 'Charges de personnel', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '661', nom: 'Rémunérations directes versées au personnel', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '66' },
  { numero: '663', nom: 'Indemnités forfaitaires versées au personnel', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '66' },
  { numero: '664', nom: 'Charges sociales patronales', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '66' },
  { numero: '665', nom: 'Avantages en nature et accessoires de salaires', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '66' },
  { numero: '666', nom: 'Cotisations au fonds de retraite', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '66' },
  { numero: '67', nom: 'Frais financiers et charges assimilées', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '671', nom: 'Intérêts des emprunts', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '67' },
  { numero: '672', nom: 'Agios et frais bancaires', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '67' },
  { numero: '675', nom: 'Pertes de change', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '67' },
  { numero: '68', nom: 'Dotations aux amortissements', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '681', nom: 'Dotations aux amortissements des immobilisations incorporelles', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '68' },
  { numero: '682', nom: 'Dotations aux amortissements des immobilisations corporelles', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '68' },
  { numero: '69', nom: 'Dotations aux provisions et pertes de valeur', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: null },
  { numero: '691', nom: 'Dotations aux provisions pour risques et charges', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '69' },
  { numero: '697', nom: 'Dotations pour dépréciation des actifs circulants', classe: TypeCompte.CLASSE_6, sens: 'DEBITEUR', parent: '69' },

  { numero: '70', nom: 'Ventes de produits fabriqués, prestations de services', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '701', nom: 'Ventes de marchandises', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '70' },
  { numero: '706', nom: 'Prestations de services', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '70' },
  { numero: '71', nom: 'Cotisations des membres', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '711', nom: 'Cotisations ordinaires', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '71' },
  { numero: '712', nom: 'Cotisations extraordinaires', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '71' },
  { numero: '713', nom: 'Droits d\'adhésion', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '71' },
  { numero: '72', nom: 'Dons et legs', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '721', nom: 'Dons reçus en numéraire', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '72' },
  { numero: '722', nom: 'Dons reçus en nature', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '72' },
  { numero: '723', nom: 'Legs et donations', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '72' },
  { numero: '73', nom: 'Subventions et financements reçus', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '731', nom: 'Subventions de fonctionnement', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '73' },
  { numero: '732', nom: 'Subventions de projets', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '73' },
  { numero: '733', nom: 'Financements reçus des bailleurs', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '73' },
  { numero: '734', nom: "Subventions d'équilibre", classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '73' },
  { numero: '74', nom: 'Revenus des activités génératrices de fonds', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '741', nom: 'Revenus des activités commerciales', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '74' },
  { numero: '742', nom: 'Revenus des activités de formation', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '74' },
  { numero: '748', nom: 'Autres activités génératrices de fonds', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '74' },
  { numero: '75', nom: 'Autres produits', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '751', nom: 'Produits de cessions d\'éléments actifs', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '75' },
  { numero: '758', nom: 'Produits divers de gestion', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '75' },
  { numero: '77', nom: 'Revenus financiers et produits assimilés', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '771', nom: 'Intérêts de prêts et créances', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '77' },
  { numero: '772', nom: 'Produits sur titres de placement', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '77' },
  { numero: '775', nom: 'Gains de change', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '77' },
  { numero: '78', nom: 'Transferts de charges', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '781', nom: 'Transferts de charges d\'exploitation', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '78' },
  { numero: '787', nom: 'Transferts de charges financières', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '78' },
  { numero: '79', nom: 'Reprises de provisions et pertes de valeur', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: null },
  { numero: '791', nom: 'Reprises de provisions pour risques et charges', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '79' },
  { numero: '797', nom: 'Reprises de pertes de valeur sur actifs circulants', classe: TypeCompte.CLASSE_7, sens: 'CREDITEUR', parent: '79' },
];
