import type { FaqItem } from './types';

/**
 * English FAQ — part 2: Business modules (20) + Imports & exports (9).
 * Same `id` values and same order as the French source (`faq.ts`).
 * Editorial rule kept from the French version: only describe what the software
 * actually does; whenever a feature depends on configuration or is not yet
 * delivered, the answer says so explicitly.
 *
 * `categorie` carries the English label, so the literal is typed locally and
 * exposed as `FaqItem[]`; the shared `CategorieFaq` union stays French-only.
 */
type FaqItemEn = Omit<FaqItem, 'categorie'> & {
  categorie: 'Business modules' | 'Imports & exports';
};

const ITEMS: FaqItemEn[] = [
  // ── Business modules ──────────────────────────────────────
  { id: 'mod-1', categorie: 'Business modules', question: 'How do I register a new member?', reponse: "Members › New member: enter at least a last name, a first name and one contact detail, select the membership category, then save.", motsCles: ['member', 'membership', 'enrolment', 'create'] },
  { id: 'mod-2', categorie: 'Business modules', question: 'How do I record a donation earmarked for a project?', reponse: "From Donors, create the donation and select the project in the earmarking field. Without an earmark, the donation stays under unrestricted resources.", motsCles: ['donation', 'earmarked', 'restricted funds', 'project', 'donor'] },
  { id: 'mod-3', categorie: 'Business modules', question: 'What is the difference between a donor and a funder?', reponse: "A donor gives a donation, usually one-off and with no contractual reporting obligation. A funder finances under a grant agreement that carries reporting requirements and deadlines.", motsCles: ['donor', 'funder', 'grant agreement', 'difference'] },
  { id: 'mod-4', categorie: 'Business modules', question: 'How do I create a project and link funding to it?', reponse: "Create the project under Projects, then record the corresponding grant agreement under Funders, linking it to that project. Earmarked donations are linked from the Donors module.", motsCles: ['project', 'funding', 'grant agreement', 'funder'] },
  { id: 'mod-5', categorie: 'Business modules', question: 'How do I post a journal entry?', reponse: "Accounting › Journal entries › New entry: choose the journal and the date, then enter the debit and credit lines. The entry cannot be saved until debits and credits are equal.", motsCles: ['journal entry', 'accounting', 'debit', 'credit', 'journal'] },
  { id: 'mod-6', categorie: 'Business modules', question: 'Why is my journal entry rejected?', reponse: "Three main causes: debits and credits do not balance, the date falls outside the open fiscal year, or the account does not exist in the chart of accounts.", motsCles: ['journal entry', 'error', 'rejected', 'out of balance'] },
  { id: 'mod-7', categorie: 'Business modules', question: 'What is the SYCEBNL framework?', reponse: "It is the accounting framework applicable to not-for-profit entities in the OHADA area. It defines the structure of the chart of accounts and of the financial statements used by the Accounting module.", motsCles: ['SYCEBNL', 'OHADA', 'accounting framework', 'standard'] },
  { id: 'mod-8', categorie: 'Business modules', question: 'How do I track budget consumption on a project?', reponse: "Create the project budget, then charge expenses to the project when posting them in accounting. The consumption rate compares actuals against the approved budget.", motsCles: ['budget', 'burn rate', 'consumption', 'project', 'variance'] },
  { id: 'mod-9', categorie: 'Business modules', question: 'How do I reconcile a bank account?', reponse: "Treasury › the relevant account: compare the recorded transactions with the bank statement for the period and clear any differences before closing the month.", motsCles: ['bank reconciliation', 'bank', 'treasury', 'statement'] },
  { id: 'mod-10', categorie: 'Business modules', question: 'In what order should a purchase be processed?', reponse: "Purchase order, then goods receipt, then invoice, then payment. This sequence provides the audit trail expected during audits and keeps stock levels correct.", motsCles: ['purchasing', 'purchase order', 'goods receipt', 'invoice'] },
  { id: 'mod-11', categorie: 'Business modules', question: 'How do I correct an incorrect stock level?', reponse: "Run a stock count under Stock: the gap between the book quantity and the physical quantity is recorded and then adjusted, which keeps an audit trail of the correction.", motsCles: ['stock', 'inventory count', 'stock discrepancy', 'adjustment'] },
  { id: 'mod-12', categorie: 'Business modules', question: 'How do I generate a payslip?', reponse: "Human resources › Employees: open the employee, check that an active contract covers the period, then generate the payslip for the selected period.", motsCles: ['payroll', 'payslip', 'HR', 'salary'] },
  { id: 'mod-13', categorie: 'Business modules', question: 'How do I record an in-kind donation?', reponse: "Record it as a donation, stating its nature and a documented valuation. If the goods enter inventory, also record the corresponding stock receipt under Stock.", motsCles: ['gift in kind', 'in-kind donation', 'valuation', 'stock'] },
  { id: 'mod-14', categorie: 'Business modules', question: 'How do I avoid counting a beneficiary twice?', reponse: "Search for the person before creating any record, and reuse the existing file by linking it to the new activity instead of creating a duplicate.", motsCles: ['beneficiary', 'duplicate', 'double counting', 'MEAL'] },
  { id: 'mod-15', categorie: 'Business modules', question: 'Why does a MEAL indicator exceed 100% achievement?', reponse: "Usually because cumulative values were entered as if they were period values. Decide on one data-entry convention (cumulative or per period) and apply it to every reading.", motsCles: ['MEAL', 'indicator', 'cumulative', 'achievement rate'] },
  { id: 'mod-16', categorie: 'Business modules', question: 'How do I record a board decision?', reponse: "Governance: record the meeting with its date and agenda, add the decisions with an owner and an implementation status, then attach the signed minutes under Documents.", motsCles: ['governance', 'board decision', 'board', 'minutes'] },
  { id: 'mod-17', categorie: 'Business modules', question: 'How do I track assets financed by a funder?', reponse: "Record them under Fixed assets and fill in the financing funder: the asset inventory can then be extracted at the end of the grant agreement.", motsCles: ['fixed asset', 'funder', 'asset inventory', 'equipment'] },
  { id: 'mod-18', categorie: 'Business modules', question: 'How do I manage attendance at an event?', reponse: "Events: add the participants, then mark attendance on the day itself. The export reflects the data as entered at the moment it is generated.", motsCles: ['event', 'attendance', 'participants'] },
  { id: 'mod-19', categorie: 'Business modules', question: 'A mobile money transaction is not matched to anyone.', reponse: "The sending number is not linked to any record. Add the phone number to the member, donor or supplier record, then run the reconciliation again.", motsCles: ['mobile money', 'reconciliation', 'phone number', 'payment'] },
  { id: 'mod-20', categorie: 'Business modules', question: 'Can a journal entry be deleted?', reponse: "Deleting posted journal entries is not acceptable accounting practice: post a reversing entry instead. Deletion rights, where they exist, should remain restricted to the administrator.", motsCles: ['delete', 'journal entry', 'reversing entry', 'cancellation'] },

  // ── Imports & exports ─────────────────────────────────────
  { id: 'imp-1', categorie: 'Imports & exports', question: 'Which modules accept a data import?', reponse: "The Data import module lists the data types currently supported by your installation. If a type is not listed, it cannot be imported.", motsCles: ['import', 'modules', 'data', 'bulk upload'] },
  { id: 'imp-2', categorie: 'Imports & exports', question: 'Which file format should I use for an import?', reponse: "A tabular file with a header row matching the expected template and one row per record. Do not rename the template columns.", motsCles: ['file format', 'CSV', 'spreadsheet', 'headers'] },
  { id: 'imp-3', categorie: 'Imports & exports', question: 'My import was rejected in full.', reponse: "In most cases the column headers do not match the template. Start again from the supplied template and copy your data into it.", motsCles: ['import', 'rejected', 'error', 'headers'] },
  { id: 'imp-4', categorie: 'Imports & exports', question: 'My dates are shifted after the import.', reponse: "The date format was ambiguous (day and month swapped). Use the YYYY-MM-DD format in the source file.", motsCles: ['date format', 'YYYY-MM-DD', 'import', 'shifted dates'] },
  { id: 'imp-5', categorie: 'Imports & exports', question: 'How do I avoid duplicates when re-importing?', reponse: "After a partially successful import, re-import only the rows that failed. Re-importing the whole file creates the already-imported records a second time.", motsCles: ['duplicates', 're-import', 'import', 'failed rows'] },
  { id: 'imp-6', categorie: 'Imports & exports', question: 'Which export formats are available?', reponse: "Depending on the screen, exports are offered as PDF for circulation and as a spreadsheet format for further processing. The export button sits above the relevant lists.", motsCles: ['export', 'PDF', 'spreadsheet', 'formats'] },
  { id: 'imp-7', categorie: 'Imports & exports', question: 'The export contains fewer rows than expected.', reponse: "The export reproduces the list exactly as filtered on screen. Clear the filters and the date range before exporting.", motsCles: ['export', 'filters', 'missing rows', 'incomplete'] },
  { id: 'imp-8', categorie: 'Imports & exports', question: 'Can I schedule a recurring export?', reponse: "No. Exports are triggered manually from the interface. No scheduling of automatic exports is available.", motsCles: ['automation', 'export', 'scheduling', 'recurring'] },
  { id: 'imp-9', categorie: 'Imports & exports', question: 'Is there an API to connect another system?', reponse: "The application runs on an internal API, but no documented external access is open by default. Contact IBIG SOFT to find out the applicable conditions.", motsCles: ['API', 'integration', 'connector', 'external system'] },
];

export const FAQ_EN_PART2: FaqItem[] = ITEMS as unknown as FaqItem[];
