import type { CategorieFaq, FaqItem } from './types';

/**
 * FAQ internes ANOUANZÊ ERP.
 * Règle de rédaction : ne décrire que ce que le logiciel fait réellement.
 * Lorsqu'une fonction dépend d'une configuration ou n'est pas encore livrée,
 * la réponse le dit explicitement.
 */
export const FAQ_ITEMS: FaqItem[] = [
  // ── Général ───────────────────────────────────────────────
  { id: 'gen-1', categorie: 'Général', question: "Qu'est-ce qu'ANOUANZÊ ERP ?", reponse: "Une solution de gestion intégrée conçue pour les organisations à but non lucratif : membres, dons, bailleurs, projets, ressources humaines, comptabilité SYCEBNL, budget, trésorerie, achats, stocks, documents et suivi-évaluation.", motsCles: ['presentation', 'definition', 'erp', 'anouanze'] },
  { id: 'gen-2', categorie: 'Général', question: 'À qui s\'adresse la solution ?', reponse: "Aux associations, ONG, fondations, coopératives et structures confessionnelles qui doivent tenir une comptabilité de type SYCEBNL et rendre compte à des bailleurs ou à leurs membres.", motsCles: ['cible', 'ong', 'association', 'fondation'] },
  { id: 'gen-3', categorie: 'Général', question: 'Faut-il installer un logiciel sur mon poste ?', reponse: "Non. L'ERP s'utilise dans un navigateur web récent (Chrome, Edge, Firefox ou Safari à jour). Aucune installation n'est nécessaire.", motsCles: ['installation', 'navigateur', 'web', 'poste'] },
  { id: 'gen-4', categorie: 'Général', question: "L'application fonctionne-t-elle sur téléphone ?", reponse: "Les écrans sont responsifs et utilisables sur mobile et tablette. La saisie de masse (comptabilité, imports) reste plus confortable sur ordinateur. Il n'existe pas d'application mobile native à installer.", motsCles: ['mobile', 'telephone', 'tablette', 'responsive'] },
  { id: 'gen-5', categorie: 'Général', question: 'Peut-on travailler hors connexion ?', reponse: "Non. Une connexion internet est nécessaire : les données sont enregistrées sur le serveur au moment de la validation.", motsCles: ['hors ligne', 'offline', 'connexion', 'internet'] },
  { id: 'gen-6', categorie: 'Général', question: 'Dans quelles langues est disponible l\'interface ?', reponse: "L'interface est en français. D'autres langues ne sont pas disponibles à ce jour.", motsCles: ['langue', 'francais', 'traduction', 'anglais'] },
  { id: 'gen-7', categorie: 'Général', question: 'Combien d\'utilisateurs peuvent travailler simultanément ?', reponse: "Plusieurs utilisateurs peuvent travailler en même temps ; le nombre de comptes autorisés dépend de votre contrat de licence. Consultez votre administrateur ou IBIG SOFT.", motsCles: ['utilisateurs', 'simultane', 'licence', 'concurrent'] },
  { id: 'gen-8', categorie: 'Général', question: 'Où trouver le numéro de version installé ?', reponse: "La version déployée est indiquée dans Paramètres. En cas de doute, mentionnez la date et l'écran concerné dans votre ticket de support.", motsCles: ['version', 'build', 'release'] },

  // ── Connexion & sécurité ──────────────────────────────────
  { id: 'sec-1', categorie: 'Connexion & sécurité', question: 'Comment réinitialiser mon mot de passe ?', reponse: "Depuis la page de connexion, utilisez « Mot de passe oublié » et saisissez votre adresse email. Si l'envoi d'email n'est pas configuré sur votre installation, demandez à votre administrateur de réinitialiser l'accès depuis Paramètres › Utilisateurs.", motsCles: ['mot de passe', 'oubli', 'reinitialiser', 'connexion'] },
  { id: 'sec-2', categorie: 'Connexion & sécurité', question: 'Pourquoi suis-je déconnecté au bout d\'un moment ?', reponse: "Le jeton d'authentification a une durée de vie limitée. Il est renouvelé automatiquement tant que votre session reste valide ; au-delà, une reconnexion est demandée pour des raisons de sécurité.", motsCles: ['session', 'expiration', 'deconnexion', 'token'] },
  { id: 'sec-3', categorie: 'Connexion & sécurité', question: 'Je reste bloqué sur un écran de chargement à la connexion.', reponse: "Videz le cache du navigateur, fermez tous les onglets de l'application puis reconnectez-vous. Si le problème persiste, ouvrez un ticket en précisant navigateur, heure et écran concerné.", motsCles: ['chargement', 'bloque', 'bug', 'connexion'] },
  { id: 'sec-4', categorie: 'Connexion & sécurité', question: 'Que faire si mon compte est désactivé ?', reponse: "Seul un administrateur peut réactiver un compte depuis Paramètres › Utilisateurs. La désactivation conserve l'historique des actions de l'utilisateur.", motsCles: ['compte', 'desactive', 'bloque', 'acces'] },
  { id: 'sec-5', categorie: 'Connexion & sécurité', question: 'Puis-je partager mon compte avec un collègue ?', reponse: "Non. Le journal d'audit attribue chaque action à un compte : le partage rend la traçabilité inexploitable et vous rend responsable des actions d'autrui. Demandez la création d'un compte dédié.", motsCles: ['partage', 'compte', 'audit', 'securite'] },
  { id: 'sec-6', categorie: 'Connexion & sécurité', question: 'La double authentification est-elle disponible ?', reponse: "L'authentification à deux facteurs n'est pas activée par défaut sur toutes les installations. Vérifiez sa disponibilité dans Paramètres › Sécurité, ou demandez confirmation à IBIG SOFT avant de vous engager auprès d'un auditeur.", motsCles: ['2fa', 'double authentification', 'mfa', 'securite'] },
  { id: 'sec-7', categorie: 'Connexion & sécurité', question: 'Comment choisir un mot de passe robuste ?', reponse: "Au moins 12 caractères mêlant majuscules, minuscules, chiffres et symboles, unique à cette application. N'utilisez pas un mot de passe déjà employé sur une messagerie ou un réseau social.", motsCles: ['mot de passe', 'robuste', 'securite', 'politique'] },
  { id: 'sec-8', categorie: 'Connexion & sécurité', question: 'Les échanges avec le serveur sont-ils chiffrés ?', reponse: "Oui lorsque l'application est servie en HTTPS, ce qui est la configuration de production recommandée. Vérifiez le cadenas dans la barre d'adresse ; signalez immédiatement toute alerte de certificat.", motsCles: ['https', 'chiffrement', 'ssl', 'certificat'] },
  { id: 'sec-9', categorie: 'Connexion & sécurité', question: 'Que faire en cas de suspicion d\'accès frauduleux ?', reponse: "Changez votre mot de passe immédiatement, prévenez l'administrateur et demandez l'extraction du journal d'audit sur la période concernée.", motsCles: ['fraude', 'intrusion', 'piratage', 'audit'] },

  // ── Utilisateurs & permissions ────────────────────────────
  { id: 'usr-1', categorie: 'Utilisateurs & permissions', question: 'Comment créer un nouvel utilisateur ?', reponse: "Paramètres › Utilisateurs › Nouveau. Renseignez l'identité et l'email, puis attribuez un rôle : sans rôle, l'utilisateur n'accède à aucun module.", motsCles: ['utilisateur', 'creation', 'compte', 'role'] },
  { id: 'usr-2', categorie: 'Utilisateurs & permissions', question: 'Quelle est la différence entre rôle et permission ?', reponse: "Une permission est un droit élémentaire sur un module (lire, créer, modifier). Un rôle est un ensemble de permissions attribué en bloc à un utilisateur.", motsCles: ['role', 'permission', 'droits', 'difference'] },
  { id: 'usr-3', categorie: 'Utilisateurs & permissions', question: 'Un utilisateur peut-il avoir plusieurs rôles ?', reponse: "La configuration des rôles dépend de votre installation. En pratique, définissez un rôle par métier plutôt que de cumuler des rôles, afin de garder les droits lisibles.", motsCles: ['multi role', 'cumul', 'droits'] },
  { id: 'usr-4', categorie: 'Utilisateurs & permissions', question: "Un menu n'apparaît pas dans ma barre latérale, pourquoi ?", reponse: "Les entrées de menu correspondant à des modules non autorisés par votre rôle ne sont pas proposées. Demandez l'ajustement de vos droits à l'administrateur.", motsCles: ['menu', 'invisible', 'droits', 'sidebar'] },
  { id: 'usr-5', categorie: 'Utilisateurs & permissions', question: 'Comment retirer l\'accès à une personne qui quitte l\'organisation ?', reponse: "Désactivez son compte plutôt que de le supprimer : l'historique et la traçabilité des écritures sont conservés.", motsCles: ['depart', 'desactivation', 'suppression', 'compte'] },
  { id: 'usr-6', categorie: 'Utilisateurs & permissions', question: 'Qui peut consulter les données de paie ?', reponse: "Seuls les profils habilités au module Ressources humaines. Les données de paie sont sensibles : limitez ce rôle au strict nécessaire.", motsCles: ['paie', 'rh', 'confidentialite', 'acces'] },
  { id: 'usr-7', categorie: 'Utilisateurs & permissions', question: 'Comment savoir qui a modifié une donnée ?', reponse: "Le module Audit liste les actions avec leur auteur, leur horodatage et l'objet concerné. Filtrez par période et par utilisateur.", motsCles: ['audit', 'tracabilite', 'modification', 'historique'] },

  // ── Paramètres ────────────────────────────────────────────
  { id: 'par-1', categorie: 'Paramètres', question: "Comment changer le logo affiché sur les documents ?", reponse: "Paramètres › Organisation : téléversez un logo. Il est repris sur les documents exportés générés après la modification.", motsCles: ['logo', 'organisation', 'documents', 'branding'] },
  { id: 'par-2', categorie: 'Paramètres', question: 'Puis-je changer la devise après avoir commencé la saisie ?', reponse: "C'est fortement déconseillé : les montants déjà enregistrés ne sont pas convertis. Si un changement est indispensable, contactez le support avant toute manipulation.", motsCles: ['devise', 'monnaie', 'changement', 'conversion'] },
  { id: 'par-3', categorie: 'Paramètres', question: 'Comment ouvrir un nouvel exercice comptable ?', reponse: "Comptabilité › Exercices : créez l'exercice avec ses dates de début et de fin. Sans exercice ouvert, aucune écriture ne peut être enregistrée sur la période.", motsCles: ['exercice', 'annee', 'ouverture', 'comptabilite'] },
  { id: 'par-4', categorie: 'Paramètres', question: 'Où définit-on les catégories de membres ou les types de documents ?', reponse: "Dans les données de référence des paramètres. Ces listes alimentent les menus déroulants des modules concernés.", motsCles: ['reference', 'categories', 'listes', 'parametrage'] },
  { id: 'par-5', categorie: 'Paramètres', question: "Une modification de paramètre n'est pas prise en compte.", reponse: "Les valeurs sont parfois conservées le temps de votre session : déconnectez-vous et reconnectez-vous, puis rechargez la page.", motsCles: ['parametre', 'cache', 'session', 'rafraichir'] },

  // ── Modules métier ────────────────────────────────────────
  { id: 'mod-1', categorie: 'Modules métier', question: 'Comment enregistrer un nouveau membre ?', reponse: "Membres › Nouveau membre : saisissez au minimum nom, prénom et un contact, choisissez la catégorie puis enregistrez.", motsCles: ['membre', 'adhesion', 'creation'] },
  { id: 'mod-2', categorie: 'Modules métier', question: 'Comment enregistrer un don affecté à un projet ?', reponse: "Depuis Donateurs, créez le don puis sélectionnez le projet dans le champ d'affectation. Sans affectation, le don reste en ressources non affectées.", motsCles: ['don', 'affectation', 'projet', 'donateur'] },
  { id: 'mod-3', categorie: 'Modules métier', question: 'Quelle différence entre donateur et bailleur ?', reponse: "Le donateur apporte un don, généralement ponctuel et sans obligation contractuelle de rapport. Le bailleur finance dans le cadre d'une convention assortie d'obligations de reporting et d'échéances.", motsCles: ['donateur', 'bailleur', 'difference', 'convention'] },
  { id: 'mod-4', categorie: 'Modules métier', question: 'Comment créer un projet et lui associer un financement ?', reponse: "Créez le projet dans Projets, puis enregistrez la convention correspondante dans Bailleurs en la rattachant à ce projet. Les dons affectés se rattachent depuis le module Donateurs.", motsCles: ['projet', 'financement', 'convention', 'bailleur'] },
  { id: 'mod-5', categorie: 'Modules métier', question: 'Comment saisir une écriture comptable ?', reponse: "Comptabilité › Écritures › Nouvelle écriture : choisissez le journal et la date, saisissez les lignes de débit et de crédit. L'enregistrement est refusé tant que débit et crédit ne sont pas égaux.", motsCles: ['ecriture', 'comptabilite', 'debit', 'credit', 'journal'] },
  { id: 'mod-6', categorie: 'Modules métier', question: "Pourquoi mon écriture est-elle refusée ?", reponse: "Trois causes principales : déséquilibre entre débit et crédit, date hors de l'exercice ouvert, ou compte inexistant au plan comptable.", motsCles: ['ecriture', 'erreur', 'refus', 'equilibre'] },
  { id: 'mod-7', categorie: 'Modules métier', question: "Qu'est-ce que le référentiel SYCEBNL ?", reponse: "C'est le système comptable applicable aux entités à but non lucratif dans l'espace OHADA. Il structure le plan de comptes et les états financiers utilisés par le module Comptabilité.", motsCles: ['sycebnl', 'ohada', 'referentiel', 'norme'] },
  { id: 'mod-8', categorie: 'Modules métier', question: 'Comment suivre la consommation budgétaire d\'un projet ?', reponse: "Créez le budget du projet, puis imputez les dépenses au projet lors de la saisie comptable. Le taux de consommation compare le réalisé au budget validé.", motsCles: ['budget', 'consommation', 'projet', 'ecart'] },
  { id: 'mod-9', categorie: 'Modules métier', question: 'Comment rapprocher un compte bancaire ?', reponse: "Trésorerie › le compte concerné : comparez les mouvements enregistrés au relevé de la période et corrigez les écarts constatés avant de clôturer le mois.", motsCles: ['rapprochement', 'banque', 'tresorerie', 'releve'] },
  { id: 'mod-10', categorie: 'Modules métier', question: 'Dans quel ordre traiter un achat ?', reponse: "Commande, puis réception, puis facture, puis règlement. Cet ordre garantit la traçabilité attendue lors des audits et la mise à jour correcte des stocks.", motsCles: ['achat', 'commande', 'reception', 'facture'] },
  { id: 'mod-11', categorie: 'Modules métier', question: 'Comment corriger un stock erroné ?', reponse: "Réalisez un inventaire dans Stocks : l'écart entre stock théorique et stock physique est constaté puis régularisé, ce qui conserve la trace de la correction.", motsCles: ['stock', 'inventaire', 'ecart', 'regularisation'] },
  { id: 'mod-12', categorie: 'Modules métier', question: 'Comment générer une fiche de paie ?', reponse: "Ressources humaines › Employés : ouvrez l'employé, vérifiez qu'un contrat actif couvre la période, puis générez le bulletin pour la période choisie.", motsCles: ['paie', 'bulletin', 'rh', 'salaire'] },
  { id: 'mod-13', categorie: 'Modules métier', question: "Comment enregistrer un don en nature ?", reponse: "Enregistrez-le comme don en précisant sa nature et une valorisation justifiée. Si le bien entre en stock, saisissez également l'entrée correspondante dans Stocks.", motsCles: ['don en nature', 'valorisation', 'stock'] },
  { id: 'mod-14', categorie: 'Modules métier', question: 'Comment éviter de compter deux fois un bénéficiaire ?', reponse: "Recherchez la personne avant toute création et réutilisez la fiche existante en la rattachant à la nouvelle activité, au lieu de créer un doublon.", motsCles: ['beneficiaire', 'doublon', 'comptage', 'meal'] },
  { id: 'mod-15', categorie: 'Modules métier', question: "Pourquoi un indicateur MEAL dépasse-t-il 100 % d'atteinte ?", reponse: "Généralement parce que des valeurs cumulées ont été saisies comme si elles étaient périodiques. Fixez un mode de saisie (cumulé ou périodique) et appliquez-le à tous les relevés.", motsCles: ['meal', 'indicateur', 'cumul', 'taux'] },
  { id: 'mod-16', categorie: 'Modules métier', question: 'Comment consigner une décision de conseil d\'administration ?', reponse: "Gouvernance : enregistrez la réunion avec sa date et son ordre du jour, ajoutez les décisions avec un responsable et un état de mise en œuvre, puis joignez le PV signé dans les Documents.", motsCles: ['gouvernance', 'decision', 'ca', 'pv'] },
  { id: 'mod-17', categorie: 'Modules métier', question: 'Comment suivre les biens financés par un bailleur ?', reponse: "Enregistrez-les dans Immobilisations en renseignant le bailleur financeur : l'inventaire pourra être extrait en fin de convention.", motsCles: ['immobilisation', 'bailleur', 'inventaire', 'bien'] },
  { id: 'mod-18', categorie: 'Modules métier', question: 'Comment gérer les présences à un événement ?', reponse: "Événements : ajoutez les participants puis pointez les présences le jour même. L'export reflète l'état de saisie au moment de la génération.", motsCles: ['evenement', 'presence', 'participants'] },
  { id: 'mod-19', categorie: 'Modules métier', question: 'Une transaction mobile money ne se rattache à personne.', reponse: "Le numéro émetteur n'est associé à aucune fiche. Complétez le numéro de téléphone sur la fiche du membre, du donateur ou du fournisseur, puis relancez le rapprochement.", motsCles: ['mobile money', 'rapprochement', 'telephone', 'paiement'] },
  { id: 'mod-20', categorie: 'Modules métier', question: 'Peut-on supprimer une écriture comptable ?', reponse: "La suppression d'écritures validées n'est pas une pratique acceptable en comptabilité : passez une écriture de contrepassation. Les droits de suppression, s'ils existent, doivent rester réservés à l'administrateur.", motsCles: ['suppression', 'ecriture', 'contrepassation', 'annulation'] },

  // ── Imports & exports ─────────────────────────────────────
  { id: 'imp-1', categorie: 'Imports & exports', question: 'Quels modules acceptent un import de données ?', reponse: "Le module Import de données présente la liste des types de données actuellement pris en charge par votre installation. Si un type n'y figure pas, il n'est pas importable.", motsCles: ['import', 'modules', 'donnees', 'masse'] },
  { id: 'imp-2', categorie: 'Imports & exports', question: 'Quel format de fichier utiliser pour un import ?', reponse: "Un fichier tabulaire avec une ligne d'en-têtes conforme au modèle attendu et une ligne par enregistrement. Ne renommez pas les colonnes du modèle.", motsCles: ['format', 'csv', 'excel', 'entetes'] },
  { id: 'imp-3', categorie: 'Imports & exports', question: "Mon import a été rejeté en totalité.", reponse: "Le plus souvent, les en-têtes de colonnes ne correspondent pas au modèle. Repartez du modèle fourni et recopiez vos données dedans.", motsCles: ['import', 'rejet', 'erreur', 'entetes'] },
  { id: 'imp-4', categorie: 'Imports & exports', question: 'Mes dates sont décalées après import.', reponse: "Le format de date était ambigu (jour et mois inversés). Utilisez le format AAAA-MM-JJ dans le fichier source.", motsCles: ['date', 'format', 'import', 'decalage'] },
  { id: 'imp-5', categorie: 'Imports & exports', question: "Comment éviter les doublons lors d'un ré-import ?", reponse: "Après un import partiellement réussi, ne réimportez que les lignes en erreur. Réimporter le fichier entier recrée les enregistrements déjà créés.", motsCles: ['doublon', 'reimport', 'import', 'erreur'] },
  { id: 'imp-6', categorie: 'Imports & exports', question: 'Quels formats d\'export sont proposés ?', reponse: "Selon les écrans, l'export est proposé en PDF pour la diffusion et en format tableur pour le retraitement. Le bouton d'export figure au-dessus des listes concernées.", motsCles: ['export', 'pdf', 'excel', 'formats'] },
  { id: 'imp-7', categorie: 'Imports & exports', question: "L'export contient moins de lignes que prévu.", reponse: "L'export reprend la liste telle qu'elle est filtrée à l'écran. Réinitialisez les filtres et la période avant d'exporter.", motsCles: ['export', 'filtre', 'lignes', 'incomplet'] },
  { id: 'imp-8', categorie: 'Imports & exports', question: 'Puis-je automatiser un export récurrent ?', reponse: "Non, les exports sont déclenchés manuellement depuis l'interface. Aucune programmation d'export automatique n'est disponible.", motsCles: ['automatisation', 'export', 'planification', 'recurrent'] },
  { id: 'imp-9', categorie: 'Imports & exports', question: 'Existe-t-il une API pour connecter un autre logiciel ?', reponse: "L'application repose sur une API interne, mais aucun accès externe documenté n'est ouvert par défaut. Adressez la demande à IBIG SOFT pour connaître les conditions.", motsCles: ['api', 'integration', 'connecteur', 'externe'] },

  // ── Documents & impressions ───────────────────────────────
  { id: 'doc-1', categorie: 'Documents & impressions', question: 'Où sont stockés les fichiers téléversés ?', reponse: "Sur le serveur qui héberge votre installation, accessibles depuis le module Documents selon vos permissions.", motsCles: ['fichiers', 'stockage', 'ged', 'documents'] },
  { id: 'doc-2', categorie: 'Documents & impressions', question: 'Mon téléversement est refusé.', reponse: "Le fichier dépasse la taille autorisée ou son format n'est pas accepté. Compressez le fichier ou convertissez-le en PDF avant de réessayer.", motsCles: ['upload', 'refus', 'taille', 'format'] },
  { id: 'doc-3', categorie: 'Documents & impressions', question: 'Comment retrouver rapidement un document ?', reponse: "Adoptez une convention de nommage stable (type_entité_date) et rattachez le document au projet, au membre ou à la convention concernée : la recherche s'appuie sur ces informations.", motsCles: ['recherche', 'document', 'nommage', 'classement'] },
  { id: 'doc-4', categorie: 'Documents & impressions', question: 'Comment imprimer un état financier ?', reponse: "Générez l'export PDF depuis Rapports & BI ou depuis le module concerné, puis imprimez le fichier obtenu.", motsCles: ['impression', 'pdf', 'etat', 'rapport'] },
  { id: 'doc-5', categorie: 'Documents & impressions', question: "Le PDF généré s'affiche mal ou est coupé.", reponse: "Vérifiez l'orientation et la largeur du tableau exporté ; réduisez le nombre de colonnes affichées avant l'export, puis relancez la génération.", motsCles: ['pdf', 'mise en page', 'coupe', 'export'] },
  { id: 'doc-6', categorie: 'Documents & impressions', question: 'Peut-on personnaliser un modèle de document ?', reponse: "L'en-tête reprend l'identité et le logo saisis dans les paramètres. La personnalisation fine des gabarits n'est pas exposée dans l'interface : formulez la demande auprès d'IBIG SOFT.", motsCles: ['modele', 'template', 'personnalisation', 'entete'] },
  { id: 'doc-7', categorie: 'Documents & impressions', question: 'Un document supprimé peut-il être récupéré ?', reponse: "Ne comptez pas dessus : traitez toute suppression comme définitive. Conservez une copie hors application des pièces contractuelles importantes.", motsCles: ['suppression', 'recuperation', 'document', 'corbeille'] },

  // ── Abonnements & licences ────────────────────────────────
  { id: 'lic-1', categorie: 'Abonnements & licences', question: 'Comment connaître les conditions de ma licence ?', reponse: "Les conditions (nombre d'utilisateurs, modules ouverts, durée) figurent dans votre contrat avec IBIG SOFT. L'application n'affiche pas le détail contractuel.", motsCles: ['licence', 'contrat', 'conditions', 'abonnement'] },
  { id: 'lic-2', categorie: 'Abonnements & licences', question: 'Que se passe-t-il si mon abonnement expire ?', reponse: "L'accès peut être suspendu conformément à votre contrat. Anticipez le renouvellement auprès d'IBIG SOFT pour éviter toute interruption d'activité.", motsCles: ['expiration', 'abonnement', 'suspension', 'renouvellement'] },
  { id: 'lic-3', categorie: 'Abonnements & licences', question: 'Comment ajouter des utilisateurs supplémentaires ?', reponse: "Si votre quota est atteint, l'ajout nécessite une extension de licence : contactez IBIG SOFT.", motsCles: ['utilisateurs', 'quota', 'extension', 'licence'] },
  { id: 'lic-4', categorie: 'Abonnements & licences', question: 'Puis-je activer un module supplémentaire ?', reponse: "L'ouverture d'un module dépend de votre contrat. Adressez la demande à IBIG SOFT, qui procède à l'activation côté installation.", motsCles: ['module', 'activation', 'option', 'licence'] },
  { id: 'lic-5', categorie: 'Abonnements & licences', question: 'Les mises à jour sont-elles incluses ?', reponse: "Les modalités de mise à jour sont définies par votre contrat de maintenance. Les déploiements sont réalisés par IBIG SOFT.", motsCles: ['mise a jour', 'maintenance', 'version', 'contrat'] },

  // ── Sauvegarde & données ──────────────────────────────────
  { id: 'sav-1', categorie: 'Sauvegarde & données', question: 'Qui réalise les sauvegardes ?', reponse: "Les sauvegardes relèvent de l'hébergement de votre installation, opéré par IBIG SOFT ou par votre prestataire. Faites-vous confirmer par écrit la fréquence et la durée de rétention.", motsCles: ['sauvegarde', 'backup', 'hebergement', 'retention'] },
  { id: 'sav-2', categorie: 'Sauvegarde & données', question: 'Puis-je déclencher une sauvegarde depuis l\'interface ?', reponse: "Non. Aucun bouton de sauvegarde manuelle n'est exposé aux utilisateurs. En revanche, vous pouvez exporter vos listes pour disposer d'une copie de travail.", motsCles: ['sauvegarde manuelle', 'bouton', 'export', 'copie'] },
  { id: 'sav-3', categorie: 'Sauvegarde & données', question: 'Comment récupérer une donnée supprimée par erreur ?', reponse: "Consultez d'abord le journal d'audit pour identifier l'action et son auteur, puis ouvrez un ticket : une restauration éventuelle dépend de la politique de sauvegarde de votre hébergement.", motsCles: ['suppression', 'restauration', 'erreur', 'audit'] },
  { id: 'sav-4', categorie: 'Sauvegarde & données', question: 'Comment récupérer mes données si je change de solution ?', reponse: "Utilisez les exports disponibles module par module. Pour une extraction complète de la base, la demande doit être adressée à IBIG SOFT.", motsCles: ['reversibilite', 'export', 'migration', 'donnees'] },
  { id: 'sav-5', categorie: 'Sauvegarde & données', question: 'Comment protéger les données personnelles collectées ?', reponse: "Limitez la collecte au strict nécessaire, restreignez les accès par les rôles, et ne diffusez pas d'exports nominatifs hors de l'organisation sans base légale.", motsCles: ['donnees personnelles', 'rgpd', 'confidentialite', 'minimisation'] },

  // ── Assistant SARA ────────────────────────────────────────
  { id: 'sara-1', categorie: 'Assistant SARA', question: 'Comment utiliser SARA ?', reponse: "Ouvrez le menu Assistant IA et posez votre question en français, en précisant le module et l'action concernés.", motsCles: ['sara', 'assistant', 'ia', 'utilisation'] },
  { id: 'sara-2', categorie: 'Assistant SARA', question: 'SARA peut-elle modifier mes données ?', reponse: "Non. SARA explique et oriente ; les créations et modifications restent effectuées par vous dans les écrans concernés.", motsCles: ['sara', 'modification', 'donnees', 'securite'] },
  { id: 'sara-3', categorie: 'Assistant SARA', question: 'Les réponses de SARA sont-elles toujours exactes ?', reponse: "Non. Un assistant conversationnel peut se tromper : vérifiez toute information sensible (comptable, juridique, réglementaire) auprès du guide utilisateur ou du support avant de l'appliquer.", motsCles: ['fiabilite', 'erreur', 'sara', 'verification'] },
  { id: 'sara-4', categorie: 'Assistant SARA', question: 'Puis-je écrire des informations confidentielles à SARA ?', reponse: "Évitez-le. Ne saisissez ni mot de passe, ni coordonnées bancaires, ni données personnelles sensibles dans la conversation.", motsCles: ['confidentialite', 'sara', 'donnees sensibles'] },
  { id: 'sara-5', categorie: 'Assistant SARA', question: 'SARA ne répond pas ou renvoie une erreur.', reponse: "Le service d'assistance conversationnelle peut être indisponible. Consultez le Centre d'aide, puis ouvrez un ticket si le blocage persiste.", motsCles: ['sara', 'panne', 'erreur', 'indisponible'] },

  // ── Support ───────────────────────────────────────────────
  { id: 'sup-1', categorie: 'Support', question: 'Comment ouvrir un ticket de support ?', reponse: "Depuis le menu Support, créez un ticket en décrivant le module, l'action réalisée, le résultat attendu et le message d'erreur exact.", motsCles: ['ticket', 'support', 'assistance', 'incident'] },
  { id: 'sup-2', categorie: 'Support', question: 'Quelles informations joindre à un ticket ?', reponse: "Écran concerné, date et heure de l'incident, compte utilisé, étapes de reproduction, capture d'écran et message d'erreur littéral. Ces éléments réduisent fortement le délai de traitement.", motsCles: ['ticket', 'informations', 'reproduction', 'capture'] },
  { id: 'sup-3', categorie: 'Support', question: 'Quel est le délai de réponse du support ?', reponse: "Le délai dépend de votre contrat de maintenance avec IBIG SOFT. Le Centre d'aide n'affiche pas d'engagement de délai.", motsCles: ['delai', 'sla', 'support', 'reponse'] },
  { id: 'sup-4', categorie: 'Support', question: 'Comment suivre l\'avancement de mon ticket ?', reponse: "Le module Support liste vos tickets avec leur statut et les échanges associés.", motsCles: ['ticket', 'statut', 'suivi', 'avancement'] },
  { id: 'sup-5', categorie: 'Support', question: 'Comment relancer la visite guidée de l\'application ?', reponse: "Depuis le Centre d'aide, utilisez le bouton de relance de la visite guidée : elle se rejoue au retour sur le tableau de bord.", motsCles: ['visite guidee', 'onboarding', 'tour', 'relance'] },
  { id: 'sup-6', categorie: 'Support', question: 'Proposez-vous des formations pour les équipes ?', reponse: "L'espace Académie regroupe les parcours de formation prévus. Les contenus vidéo ne sont pas encore publiés ; les sessions accompagnées se demandent auprès d'IBIG SOFT.", motsCles: ['formation', 'academie', 'session', 'equipe'] },
  { id: 'sup-7', categorie: 'Support', question: 'Comment signaler une anomalie de calcul ?', reponse: "Ouvrez un ticket en joignant l'export concerné, la valeur attendue, la valeur obtenue et les filtres appliqués : sans ces éléments, l'anomalie n'est pas reproductible.", motsCles: ['anomalie', 'calcul', 'bug', 'ticket'] },
  { id: 'sup-8', categorie: 'Support', question: 'Comment demander une nouvelle fonctionnalité ?', reponse: "Ouvrez un ticket de type évolution en décrivant le besoin métier et l'usage attendu. La priorisation relève d'IBIG SOFT.", motsCles: ['evolution', 'fonctionnalite', 'demande', 'roadmap'] },
];

export const CATEGORIES_FAQ: CategorieFaq[] = [
  'Général',
  'Connexion & sécurité',
  'Utilisateurs & permissions',
  'Paramètres',
  'Modules métier',
  'Imports & exports',
  'Documents & impressions',
  'Abonnements & licences',
  'Sauvegarde & données',
  'Assistant SARA',
  'Support',
];
