import type { GuideModule } from './types';

/**
 * English user guide — part 2: Finance, Tools, Administration.
 *
 * Same conventions as `guide.en.part1.ts`: identical `id` values and order to
 * the French source, canonical French `categorie` identifiers, English sidebar
 * labels in the navigation paths.
 */
export const GUIDE_EN_PART2: GuideModule[] = [
  {
    id: 'comptabilite',
    titre: 'SYCEBNL accounting',
    href: '/comptabilite',
    categorie: 'Finance',
    objectif:
      'Keep accounts compliant with the SYCEBNL framework: chart of accounts, journals, entries and financial statements.',
    utilisateurs: ['Accountant', 'Finance director', 'Auditor (read only)'],
    prerequis: [
      'Financial year open',
      'Chart of accounts initialised',
      'Journals created (purchases, sales, bank, cash, general)',
    ],
    procedure: [
      { titre: 'Check the chart of accounts', detail: 'Make sure the accounts your organisation uses exist before the first entry.', chemin: 'Accounting › Chart of accounts' },
      { titre: 'Create a journal entry', detail: 'Select the journal and the date, then enter the debit and credit lines.', chemin: 'Accounting › Journal entries › New entry' },
      { titre: 'Balance the entry', detail: 'Total debits must equal total credits; otherwise the entry is rejected on save.' },
      { titre: 'Fill in the analytical dimensions', detail: 'Project and funder make it possible to track restricted funds.' },
      { titre: 'Review the general ledger and trial balance', detail: 'Filter by account, journal or period to check the balances.' },
      { titre: 'Produce the financial statements', detail: 'The statements are generated from the approved entries for the period.' },
    ],
    erreurs: [
      { probleme: 'Entry rejected on save', cause: 'Debits and credits do not match, or the account does not exist', solution: 'Correct the amounts or create the missing account.' },
      { probleme: 'Entry outside the period', cause: 'Date falls outside the open financial year', solution: 'Correct the date or open the relevant financial year.' },
      { probleme: 'Restricted funds not tracked', cause: 'Project dimension left blank', solution: 'Fill in the project on the lines concerned.' },
    ],
    conseils: [
      'Post as you go: catching up on several months at once multiplies the errors.',
      'Reconcile the bank every month before producing any statement.',
      'Use the general journal only for adjustments.',
    ],
    permissions: ['Accountant role for data entry', 'Finance director role for approval', 'Read-only access for auditors'],
  },
  {
    id: 'budget',
    titre: 'Budget',
    href: '/budget',
    categorie: 'Finance',
    objectif: 'Build annual and project budgets, then monitor the variances.',
    utilisateurs: ['Finance director', 'Project officer'],
    prerequis: ['Financial year open', 'Projects created for project budgets'],
    procedure: [
      { titre: 'Create the budget', detail: 'Choose the scope — organisation or project — and the period.', chemin: 'Budget › New' },
      { titre: 'Enter the budget lines', detail: 'Each line carries a description, an account and a planned amount.' },
      { titre: 'Approve the budget', detail: 'An approved budget serves as the reference for variance calculation.' },
      { titre: 'Monitor the actuals', detail: 'Actuals come from the journal entries posted over the period.' },
      { titre: 'Analyse the variances', detail: 'The monitoring view highlights over-consumed and under-consumed lines.' },
    ],
    erreurs: [
      { probleme: 'Actuals are empty', cause: 'Budget accounts differ from the accounts actually posted to', solution: 'Align the budget accounts with the ones used in data entry.' },
      { probleme: 'Implausible variance', cause: 'Budget period differs from the period being analysed', solution: 'Check the start and end dates of the budget.' },
    ],
    conseils: [
      'One budget per grant agreement makes the required financial reports easier to produce.',
      'Revise a budget during the year through a revised version rather than by overwriting the original.',
    ],
    permissions: ['Budget write access', 'Accounting read access'],
  },
  {
    id: 'tresorerie',
    titre: 'Treasury',
    href: '/tresorerie',
    categorie: 'Finance',
    objectif: 'Track bank and cash accounts, their movements and their balances.',
    utilisateurs: ['Accountant', 'Cashier', 'Finance director'],
    prerequis: ['Treasury accounts created with their opening balance'],
    procedure: [
      { titre: 'Create the accounts', detail: 'Bank, cash, mobile money: each account has a name and a currency.', chemin: 'Treasury › Accounts' },
      { titre: 'Record the movements', detail: 'Receipts and disbursements with date, amount, description and supporting document.' },
      { titre: 'Carry out a reconciliation', detail: 'Compare the recorded movements with the bank statement for the period.' },
      { titre: 'Monitor the balances', detail: 'Balances per account and the overall position are shown at the top of the module.' },
    ],
    erreurs: [
      { probleme: 'Balance differs from the statement', cause: 'Missing movements, or movements entered twice', solution: 'Reconcile line by line and correct the differences found.' },
      { probleme: 'Negative cash balance', cause: 'Disbursement dated before the matching receipt', solution: 'Correct the value dates of the movements.' },
    ],
    conseils: ['Reconcile at least once a month; a late reconciliation makes corrections expensive.'],
    permissions: ['Treasury write access', 'Approval reserved for the finance manager'],
  },
  {
    id: 'paiements',
    titre: 'Mobile payments',
    href: '/paiements',
    categorie: 'Finance',
    objectif: 'Track mobile money receipts and disbursements and reconcile them with the treasury.',
    utilisateurs: ['Accountant', 'Cashier'],
    prerequis: ['A treasury account dedicated to mobile money', 'Phone numbers filled in on the records'],
    procedure: [
      { titre: 'Review the transactions', detail: 'The list shows the direction, the amount, the counterparty and the status.', chemin: 'Mobile payments' },
      { titre: 'Reconcile a transaction', detail: 'Match the transaction to the member, donor or supplier concerned.' },
      { titre: 'Post it to the accounts', detail: 'Once matched, the transaction feeds the corresponding treasury account.' },
    ],
    erreurs: [
      { probleme: 'Transaction cannot be matched', cause: 'The sending number is unknown to the system', solution: 'Add the number to the record, then run the matching again.' },
      { probleme: 'Duplicate with a manual entry', cause: 'The movement was already recorded in Treasury', solution: 'Delete the manual entry and keep the matched transaction.' },
    ],
    conseils: ['Check unmatched transactions daily: their volume grows quickly.'],
    permissions: ['Treasury / Payments write access'],
  },
  {
    id: 'achats',
    titre: 'Purchasing & suppliers',
    href: '/achats',
    categorie: 'Finance',
    objectif: 'Keep spending under control: requisition, purchase order, goods receipt and supplier invoice.',
    utilisateurs: ['Logistics manager', 'Accountant', 'Management'],
    prerequis: ['Suppliers created', 'Budget available on the line concerned'],
    procedure: [
      { titre: 'Create the supplier', detail: 'Legal name, contacts, payment details.', chemin: 'Purchasing › Suppliers' },
      { titre: 'Issue a purchase order', detail: 'Items, quantities, unit prices and project allocation.' },
      { titre: 'Receive the goods', detail: 'The goods receipt updates the stock for items held in inventory.' },
      { titre: 'Record the invoice', detail: 'The invoice is matched against the purchase order and the goods receipt.' },
      { titre: 'Pay', detail: 'The payment generates the corresponding treasury movement.' },
    ],
    erreurs: [
      { probleme: 'Invoice higher than the purchase order', cause: 'Price or quantity discrepancy', solution: 'Justify the discrepancy, or have the invoice corrected before approval.' },
      { probleme: 'Stock not updated', cause: 'Goods receipt not recorded', solution: 'Record the goods receipt before the invoice.' },
    ],
    conseils: ['Follow the order → receipt → invoice sequence: it is what makes the audit trail work.'],
    permissions: ['Purchasing write access', 'Approval by an authorised profile above a defined threshold'],
  },
  {
    id: 'stocks',
    titre: 'Stock',
    href: '/stocks',
    categorie: 'Finance',
    objectif: 'Track items, receipts and issues, and stock levels by store.',
    utilisateurs: ['Storekeeper', 'Logistics'],
    prerequis: ['Items and stores created'],
    procedure: [
      { titre: 'Create the items', detail: 'Reference, description, unit and reorder threshold.', chemin: 'Stock › Items' },
      { titre: 'Record the receipts', detail: 'Goods received from purchases, or in-kind donations.' },
      { titre: 'Record the issues', detail: 'Distribution, internal consumption or transfer between stores.' },
      { titre: 'Carry out a stock count', detail: 'The gap between book stock and physical stock is recorded and then adjusted.' },
    ],
    erreurs: [
      { probleme: 'Negative stock', cause: 'Issue recorded before the matching receipt', solution: 'Correct the chronology of the movements.' },
      { probleme: 'Recurring stock-count discrepancy', cause: 'Issues not recorded', solution: 'Require an entry at the time of every physical issue.' },
    ],
    conseils: ['A reorder threshold per item avoids running out of critical inputs.'],
    permissions: ['Stock write access'],
  },
  {
    id: 'immobilisations',
    titre: 'Fixed assets',
    href: '/immobilisations',
    categorie: 'Finance',
    objectif: 'List the durable assets, what they are assigned to and their depreciation.',
    utilisateurs: ['Accountant', 'Logistics'],
    prerequis: ['Fixed-asset and depreciation accounts available in the chart of accounts'],
    procedure: [
      { titre: 'Record the asset', detail: 'Description, acquisition date, value, depreciation period and location.', chemin: 'Fixed assets › New' },
      { titre: 'Assign the asset', detail: 'Department, project or funding funder — useful for end-of-agreement reports.' },
      { titre: 'Track the depreciation', detail: 'The depreciation schedule follows from the value and the period entered.' },
      { titre: 'Dispose of an asset', detail: 'Sale, write-off or transfer, with a date and a reason.' },
    ],
    erreurs: [
      { probleme: 'Depreciation not calculated', cause: 'Missing depreciation period or acquisition date', solution: 'Complete the asset record.' },
    ],
    conseils: ['Photograph and reference funder-financed assets: some funders require an inventory at the end of a project.'],
    permissions: ['Fixed assets write access', 'Accounting read access'],
  },
  {
    id: 'documents',
    titre: 'Documents (document library)',
    href: '/documents',
    categorie: 'Outils',
    objectif: 'Centralise and retrieve records: contracts, grant agreements, minutes, supporting documents.',
    utilisateurs: ['All authorised profiles'],
    prerequis: ['Filing structure defined'],
    procedure: [
      { titre: 'Upload a document', detail: 'Select the file and enter its type and its label.', chemin: 'Documents' },
      { titre: 'File it', detail: 'Attach the document to a project, a member or a grant agreement, as appropriate.' },
      { titre: 'Search', detail: 'The search covers the label and the metadata entered.' },
      { titre: 'Download or share', detail: 'Access depends on the permissions of the profile logged in.' },
    ],
    erreurs: [
      { probleme: 'Document cannot be found', cause: 'Label too generic, or not filed at all', solution: 'Adopt a naming convention: type_entity_date.' },
      { probleme: 'Upload rejected', cause: 'File too large or format not allowed', solution: 'Compress the file or convert it to PDF.' },
    ],
    conseils: ['Name the files before uploading: renaming afterwards takes longer.'],
    permissions: ['Documents read/write access depending on the role'],
  },
  {
    id: 'meal',
    titre: 'MEAL — monitoring & evaluation',
    href: '/meal',
    categorie: 'Outils',
    objectif: 'Define the indicators, collect the values and measure project results.',
    utilisateurs: ['MEAL manager', 'Project officer'],
    prerequis: ['Projects created with their logical framework'],
    procedure: [
      { titre: 'Create the indicators', detail: 'Description, unit, baseline value and target.', chemin: 'MEAL › Indicators' },
      { titre: 'Plan the data collection', detail: 'Measurement frequency and the person responsible for the data.' },
      { titre: 'Enter the values', detail: 'Every reading is dated and linked to the period concerned.' },
      { titre: 'Analyse', detail: 'The achievement rate compares the value recorded with the target.' },
    ],
    erreurs: [
      { probleme: 'Achievement rate above 100%', cause: 'Cumulative values entered as periodic ones', solution: 'Choose explicitly between cumulative and periodic, and stay consistent.' },
      { probleme: 'Indicator with no value', cause: 'Data collection not carried out', solution: 'Assign an owner and a collection deadline.' },
    ],
    conseils: ['An indicator with no documented means of verification will be challenged in an external evaluation.'],
    permissions: ['MEAL write access', 'Projects read access'],
  },
  {
    id: 'reporting',
    titre: 'Reports & BI',
    href: '/reporting',
    categorie: 'Outils',
    objectif: 'Produce dashboards and consolidated reports from the data entered.',
    utilisateurs: ['Management', 'Finance director', 'MEAL'],
    prerequis: ['Data entered and up to date in the source modules'],
    procedure: [
      { titre: 'Choose the report', detail: 'Financial, activity, project or member reports.', chemin: 'Reports & BI' },
      { titre: 'Filter', detail: 'Period, project, funder or department, depending on the report.' },
      { titre: 'Analyse', detail: 'Charts and tables recalculate according to the filters applied.' },
      { titre: 'Export', detail: 'PDF export for circulation, spreadsheet for further processing.' },
    ],
    erreurs: [
      { probleme: 'Empty report', cause: 'Filters too restrictive, or a period with no data', solution: 'Widen the period and reset the filters.' },
      { probleme: 'Discrepancy between two reports', cause: 'Different scopes or reference dates', solution: 'Compare the filters applied before concluding that something is wrong.' },
    ],
    conseils: ['A report is only as good as the data entered: check the source modules first.'],
    permissions: ['Read access to the modules covered by the report'],
  },
  {
    id: 'import-export',
    titre: 'Data import & export',
    href: '/import',
    categorie: 'Outils',
    objectif: 'Load data in bulk and extract lists for use outside the ERP.',
    utilisateurs: ['Administrator', 'Module owner'],
    prerequis: ['Source file cleaned up', 'Column template respected'],
    procedure: [
      { titre: 'Choose the data type', detail: 'Select the module the import is targeting.', chemin: 'Data import' },
      { titre: 'Prepare the file', detail: 'One row per record, with headers matching the expected template.' },
      { titre: 'Upload and check', detail: 'Rows in error are flagged before anything is committed.' },
      { titre: 'Confirm the import', detail: 'Only valid rows are created.' },
      { titre: 'Export', detail: 'From each module, the export button produces the filtered list.' },
    ],
    erreurs: [
      { probleme: 'Import rejected in full', cause: 'Headers do not match', solution: 'Start again from the expected column template without renaming the headers.' },
      { probleme: 'Dates shifted', cause: 'Ambiguous date format (day and month swapped)', solution: 'Use the unambiguous YYYY-MM-DD format.' },
      { probleme: 'Duplicates created', cause: 'Import run again after a partial success', solution: 'Re-import only the rows that failed.' },
    ],
    conseils: [
      'Always test on 5 to 10 rows before the full import.',
      'Keep the source file that was imported: it is your evidence in the event of a control.',
    ],
    permissions: ['Administrator role, or import rights on the module'],
  },
  {
    id: 'ia',
    titre: 'SARA assistant',
    href: '/ia',
    categorie: 'Outils',
    objectif: 'Get explanations about the ERP and help finding your way around it.',
    utilisateurs: ['All users'],
    prerequis: ['Being logged in'],
    procedure: [
      { titre: 'Open the assistant', detail: 'From the AI Assistant menu.', chemin: 'AI Assistant' },
      { titre: 'Ask a question', detail: 'Word the question clearly and say which module it concerns.' },
      { titre: 'Follow the guidance', detail: 'SARA points you to the right screen; the actions are still carried out by the user.' },
    ],
    erreurs: [
      { probleme: 'Answer too general', cause: 'Question too vague', solution: 'State the module, the action and the exact error message.' },
    ],
    conseils: [
      'Do not share sensitive personal information in these exchanges.',
      'For a blocking incident, raise a support ticket rather than pressing on with the assistant.',
    ],
    permissions: ['AI Assistant access'],
  },
  {
    id: 'audit',
    titre: 'Audit log',
    href: '/audit',
    categorie: 'Administration',
    objectif: 'Review the trace of the actions carried out in the system.',
    utilisateurs: ['Administrator', 'Internal auditor'],
    prerequis: ['Right to view the log'],
    procedure: [
      { titre: 'Open the log', detail: 'Entries list the author, the action, the object and the timestamp.', chemin: 'Audit' },
      { titre: 'Filter', detail: 'By user, period or type of action.' },
      { titre: 'Export', detail: 'Extract the selection for a control assignment.' },
    ],
    erreurs: [
      { probleme: 'Expected action missing from the log', cause: 'Wrong period or wrong user filter', solution: 'Widen the period and remove the filters.' },
    ],
    conseils: ['Check the log after any data incident, before reconstructing anything by hand.'],
    permissions: ['Administrator or Auditor role'],
  },
  {
    id: 'parametres',
    titre: 'Settings & administration',
    href: '/parametres',
    categorie: 'Administration',
    objectif: 'Configure the organisation, the users, the roles and the reference data.',
    utilisateurs: ['Administrator'],
    prerequis: ['Administrator role'],
    procedure: [
      { titre: 'Organisation', detail: 'Identity, logo and contact details used on documents.', chemin: 'Settings › Organisation' },
      { titre: 'Users', detail: 'Creating, deactivating and resetting access.', chemin: 'Settings › Users' },
      { titre: 'Roles and permissions', detail: 'Each role groups read and write rights by module.' },
      { titre: 'Reference data', detail: 'Categories, journals, document types and other shared lists.' },
      { titre: 'Security', detail: 'Password rules and session options.' },
    ],
    erreurs: [
      { probleme: 'User has no access after being created', cause: 'No role assigned', solution: 'Assign a role, then ask the user to log out and back in.' },
      { probleme: 'A settings change has no effect', cause: 'Current session still holding the old values', solution: 'Log out and log back in.' },
    ],
    conseils: [
      'Apply the principle of least privilege: a broad role is a risk.',
      'Deactivate the accounts of people who have left rather than sharing them.',
    ],
    permissions: ['Administrator role only'],
  },
];
