import type { GuideModule } from './types';

/**
 * Guide utilisateur module par module.
 * Le contenu décrit uniquement des fonctionnalités présentes dans l'ERP.
 */
export const GUIDE_MODULES: GuideModule[] = [
  {
    id: 'demarrage',
    titre: 'Démarrage & première configuration',
    href: '/dashboard',
    categorie: 'Démarrage',
    objectif:
      "Rendre l'ERP exploitable par l'organisation : identité, exercice comptable, utilisateurs et données de référence.",
    utilisateurs: ['Administrateur', 'Direction'],
    prerequis: [
      'Compte administrateur créé et mot de passe personnalisé',
      "Informations légales de l'organisation (raison sociale, adresse, contacts)",
      "Choix de l'exercice comptable en cours",
    ],
    procedure: [
      { titre: "Renseigner l'identité de l'organisation", detail: "Nom, sigle, adresse, téléphone, email et logo affiché sur les documents exportés.", chemin: 'Paramètres › Organisation' },
      { titre: 'Définir la devise et le format des montants', detail: "La devise sert de référence à tous les modules financiers ; la modifier après saisie d'écritures est déconseillé.", chemin: 'Paramètres › Général' },
      { titre: "Ouvrir l'exercice comptable", detail: "Créez l'exercice en cours avant toute écriture, sinon les journaux refusent la saisie.", chemin: 'Comptabilité › Exercices' },
      { titre: 'Créer les utilisateurs et attribuer les rôles', detail: "Un rôle par métier : chaque utilisateur ne voit que les modules autorisés.", chemin: 'Paramètres › Utilisateurs' },
      { titre: 'Importer les données existantes', detail: "Membres, donateurs et plan comptable peuvent être chargés depuis un fichier avant la mise en service.", chemin: 'Import de données' },
      { titre: 'Suivre la visite guidée', detail: "La visite guidée présente les zones clés du tableau de bord ; elle peut être relancée depuis le Centre d'aide." },
    ],
    erreurs: [
      { probleme: "Impossible d'enregistrer une écriture", cause: "Aucun exercice comptable ouvert", solution: "Créez l'exercice dans Comptabilité › Exercices puis réessayez." },
      { probleme: 'Les documents exportés ne portent pas le logo', cause: "Logo non téléversé dans les paramètres d'organisation", solution: 'Ajoutez le logo dans Paramètres › Organisation.' },
    ],
    conseils: [
      "Configurez d'abord les paramètres, puis importez, puis ouvrez l'accès aux utilisateurs finaux.",
      'Faites un import de test sur quelques lignes avant un import massif.',
    ],
    permissions: ['Rôle Administrateur'],
  },
  {
    id: 'membres',
    titre: 'Membres',
    href: '/membres',
    categorie: 'Relations',
    objectif: "Tenir le registre des membres, suivre les adhésions et les cotisations.",
    utilisateurs: ['Secrétariat', 'Administrateur', 'Direction'],
    prerequis: ['Catégories de membres et montants de cotisation définis dans les paramètres'],
    procedure: [
      { titre: 'Ouvrir la liste des membres', detail: 'La liste affiche nom, catégorie, statut et date d\'adhésion, avec recherche et filtres.', chemin: 'Membres' },
      { titre: 'Créer un membre', detail: 'Renseignez au minimum nom, prénom et un moyen de contact. Les champs obligatoires sont signalés.', chemin: 'Membres › Nouveau membre' },
      { titre: "Enregistrer l'adhésion", detail: "Sélectionnez la catégorie et la date d'adhésion ; le statut passe à actif." },
      { titre: 'Suivre les cotisations', detail: "Chaque cotisation encaissée est rattachée au membre et à la période concernée." },
      { titre: 'Exporter le registre', detail: "Le bouton d'export produit la liste filtrée au format PDF ou tableur." },
    ],
    erreurs: [
      { probleme: 'Doublon de membre', cause: 'Création répétée sans recherche préalable', solution: 'Recherchez le nom avant toute création ; fusionnez ou désactivez le doublon.' },
      { probleme: "Membre absent des listes", cause: 'Filtre de statut actif appliqué', solution: 'Réinitialisez les filtres pour afficher aussi les membres inactifs.' },
    ],
    conseils: [
      'Normalisez la saisie des noms (majuscules, accents) pour fiabiliser les recherches.',
      'Renseignez le téléphone : il sert aux rapprochements avec les paiements mobiles.',
    ],
    permissions: ['Lecture Membres pour consulter', 'Écriture Membres pour créer ou modifier'],
  },
  {
    id: 'donateurs',
    titre: 'Donateurs & dons',
    href: '/donateurs',
    categorie: 'Relations',
    objectif: 'Enregistrer les dons, suivre les donateurs et produire les reçus.',
    utilisateurs: ['Mobilisation de ressources', 'Comptabilité'],
    prerequis: ['Comptes de trésorerie créés', 'Exercice comptable ouvert'],
    procedure: [
      { titre: 'Créer la fiche donateur', detail: 'Personne physique ou morale, avec coordonnées et éventuelle affectation préférée.', chemin: 'Donateurs › Nouveau' },
      { titre: 'Enregistrer un don', detail: 'Montant, date, nature (numéraire ou nature), mode de règlement et affectation éventuelle à un projet.' },
      { titre: 'Affecter le don', detail: "Un don affecté est rattaché à un projet : il apparaît dans le suivi budgétaire de ce projet." },
      { titre: 'Éditer le reçu', detail: "Le reçu reprend l'identité de l'organisation, le montant et la date." },
      { titre: 'Analyser la collecte', detail: 'Les totaux par période et par donateur sont visibles dans le module et dans Rapports & BI.' },
    ],
    erreurs: [
      { probleme: 'Don non visible dans le projet', cause: 'Don enregistré sans affectation', solution: "Modifiez le don et sélectionnez le projet concerné." },
      { probleme: 'Montant incohérent après saisie', cause: 'Séparateur décimal ou espaces dans le champ montant', solution: 'Saisissez le montant sans espace ni symbole de devise.' },
    ],
    conseils: [
      'Distinguez dès la saisie les dons affectés des dons non affectés : la distinction est structurante en SYCEBNL.',
      'Enregistrez les dons en nature avec une valorisation justifiée et documentée.',
    ],
    permissions: ['Écriture Dons', 'Lecture Comptabilité pour le rapprochement'],
  },
  {
    id: 'bailleurs',
    titre: 'Bailleurs & conventions',
    href: '/bailleurs',
    categorie: 'Relations',
    objectif: 'Gérer les bailleurs institutionnels, leurs conventions et les échéances de reporting.',
    utilisateurs: ['Direction', 'Chargé de programmes', 'Comptabilité'],
    prerequis: ['Projets créés pour rattacher les conventions'],
    procedure: [
      { titre: 'Créer le bailleur', detail: 'Nom, type, pays et contacts référents.', chemin: 'Bailleurs › Nouveau' },
      { titre: 'Enregistrer la convention', detail: 'Montant, devise, dates de début et de fin, projet financé.' },
      { titre: 'Suivre les tranches de financement', detail: 'Chaque versement attendu ou reçu est daté et rattaché à la convention.' },
      { titre: 'Suivre les obligations de rapport', detail: 'Les échéances de rapport narratif et financier sont listées avec leur statut.' },
    ],
    erreurs: [
      { probleme: "Total conventionné différent du budget projet", cause: 'Budget projet saisi indépendamment de la convention', solution: 'Alignez le budget du projet sur le montant conventionné.' },
      { probleme: 'Convention sans projet', cause: 'Projet non créé au moment de la saisie', solution: 'Créez le projet puis rattachez la convention.' },
    ],
    conseils: [
      'Archivez la convention signée dans la GED et référencez-la depuis la fiche.',
      'Anticipez les échéances de rapport de 15 jours pour la consolidation des données.',
    ],
    permissions: ['Lecture/Écriture Bailleurs', 'Lecture Projets'],
  },
  {
    id: 'beneficiaires',
    titre: 'Bénéficiaires',
    href: '/beneficiaires',
    categorie: 'Relations',
    objectif: "Recenser les personnes et groupes touchés par les activités et éviter les doubles comptages.",
    utilisateurs: ['Équipes terrain', 'MEAL'],
    prerequis: ['Projets et activités créés'],
    procedure: [
      { titre: 'Enregistrer un bénéficiaire', detail: 'Identité, localisation, catégorie et projet de rattachement.', chemin: 'Bénéficiaires › Nouveau' },
      { titre: 'Rattacher aux activités', detail: "Le rattachement permet de consolider les effectifs par projet." },
      { titre: 'Consolider les effectifs', detail: 'Les totaux désagrégés alimentent les indicateurs MEAL.' },
    ],
    erreurs: [
      { probleme: 'Effectifs surévalués', cause: 'Même personne saisie sur plusieurs activités sans identifiant commun', solution: "Recherchez la personne avant création et réutilisez la fiche existante." },
    ],
    conseils: [
      'Limitez la collecte aux données réellement nécessaires (minimisation des données personnelles).',
      "Documentez la base légale ou le consentement de collecte lorsque c'est requis.",
    ],
    permissions: ['Écriture Bénéficiaires'],
  },
  {
    id: 'projets',
    titre: 'Projets',
    href: '/projets',
    categorie: 'Activités',
    objectif: 'Piloter le cycle de vie des projets : cadrage, budget, activités et avancement.',
    utilisateurs: ['Chargé de projets', 'Direction', 'MEAL'],
    prerequis: ['Bailleur ou source de financement identifié', 'Exercice comptable ouvert pour le suivi financier'],
    procedure: [
      { titre: 'Créer le projet', detail: 'Intitulé, dates, zone d\'intervention, responsable et statut.', chemin: 'Projets › Nouveau projet' },
      { titre: 'Définir le budget', detail: 'Le budget par ligne sert de référence au suivi des consommations.', chemin: 'Budget' },
      { titre: 'Planifier les activités', detail: 'Chaque activité porte une période, un responsable et un état d\'avancement.' },
      { titre: 'Rattacher les financements', detail: 'Conventions bailleurs et dons affectés viennent alimenter le projet.' },
      { titre: 'Suivre la consommation', detail: 'Les dépenses imputées au projet alimentent le taux de consommation budgétaire.' },
    ],
    erreurs: [
      { probleme: 'Taux de consommation à 0 %', cause: 'Dépenses saisies sans imputation projet', solution: "Reprenez les écritures et renseignez l'axe analytique projet." },
      { probleme: 'Projet clôturé encore modifiable', cause: 'Statut non mis à jour', solution: 'Passez le statut du projet à clôturé après la validation finale.' },
    ],
    conseils: [
      "Créez le projet avant les premières dépenses : l'imputation rétroactive est chronophage.",
      "Nommez les projets avec un code court et stable (ex. PRJ-2026-01) réutilisé partout.",
    ],
    permissions: ['Écriture Projets', 'Lecture Budget et Comptabilité pour le suivi financier'],
  },
  {
    id: 'rh',
    titre: 'Ressources humaines',
    href: '/rh',
    categorie: 'Activités',
    objectif: 'Gérer le dossier du personnel, les contrats, les congés et les éléments de paie.',
    utilisateurs: ['Responsable RH', 'Direction'],
    prerequis: ['Paramètres RH renseignés (types de contrat, rubriques de paie)'],
    procedure: [
      { titre: 'Créer le dossier employé', detail: 'Identité, poste, service, date d\'entrée et coordonnées.', chemin: 'Ressources humaines › Employés' },
      { titre: 'Enregistrer le contrat', detail: 'Type, durée, salaire de base et rattachement éventuel à un projet.' },
      { titre: 'Suivre les absences et congés', detail: 'Les demandes sont enregistrées puis validées par le responsable.' },
      { titre: 'Préparer la paie', detail: 'Sélectionnez la période, vérifiez les éléments variables puis générez les bulletins.' },
      { titre: 'Comptabiliser la paie', detail: 'Les charges de personnel sont reportées en comptabilité selon le paramétrage.' },
    ],
    erreurs: [
      { probleme: 'Bulletin non généré', cause: 'Contrat absent ou période déjà traitée', solution: "Vérifiez l'existence d'un contrat actif sur la période." },
      { probleme: 'Charges non ventilées par projet', cause: 'Aucune clé de répartition renseignée', solution: "Renseignez l'affectation projet sur le contrat ou l'écriture." },
    ],
    conseils: [
      'Verrouillez une période de paie une fois les bulletins validés.',
      "Conservez les pièces justificatives (contrats, avenants) dans la GED.",
    ],
    permissions: ['Rôle RH ou Administrateur', 'Accès restreint : les données de paie sont sensibles'],
  },
  {
    id: 'evenements',
    titre: 'Événements',
    href: '/evenements',
    categorie: 'Activités',
    objectif: 'Organiser assemblées, formations et activités publiques, avec participants et budget.',
    utilisateurs: ['Secrétariat', 'Chargé de communication'],
    prerequis: ['Membres ou bénéficiaires enregistrés pour la liste des participants'],
    procedure: [
      { titre: "Créer l'événement", detail: 'Intitulé, type, dates, lieu et responsable.', chemin: 'Événements › Nouveau' },
      { titre: 'Gérer les participants', detail: 'Ajoutez les inscrits et pointez les présences.' },
      { titre: 'Suivre le budget', detail: 'Les dépenses liées peuvent être imputées à l\'événement ou au projet porteur.' },
      { titre: 'Clôturer et archiver', detail: 'Compte rendu et pièces jointes sont conservés dans la GED.' },
    ],
    erreurs: [
      { probleme: 'Liste de présence incomplète', cause: 'Participants ajoutés après la tenue', solution: "Pointez les présences le jour même, l'export reflète la dernière saisie." },
    ],
    conseils: ["Pour une assemblée générale, reliez l'événement au module Gouvernance pour conserver les décisions."],
    permissions: ['Écriture Événements'],
  },
  {
    id: 'gouvernance',
    titre: 'Gouvernance',
    href: '/gouvernance',
    categorie: 'Activités',
    objectif: 'Documenter les instances, mandats, réunions statutaires et décisions.',
    utilisateurs: ['Direction', 'Secrétariat exécutif', 'Membres du bureau'],
    prerequis: ['Organes et mandats définis dans les statuts'],
    procedure: [
      { titre: 'Déclarer les instances', detail: 'Assemblée générale, conseil d\'administration, bureau, commissions.', chemin: 'Gouvernance' },
      { titre: 'Enregistrer les mandats', detail: 'Titulaire, fonction, date de début et de fin de mandat.' },
      { titre: 'Consigner les réunions', detail: 'Date, ordre du jour, présents et procès-verbal.' },
      { titre: 'Suivre les décisions', detail: 'Chaque décision porte un responsable et un état de mise en œuvre.' },
    ],
    erreurs: [
      { probleme: 'Mandat expiré toujours actif', cause: 'Date de fin non renseignée', solution: 'Complétez la date de fin ou renouvelez le mandat.' },
    ],
    conseils: ['Rattachez systématiquement le PV signé (GED) à la réunion correspondante.'],
    permissions: ['Lecture Gouvernance pour les membres, Écriture pour le secrétariat'],
  },
  {
    id: 'comptabilite',
    titre: 'Comptabilité SYCEBNL',
    href: '/comptabilite',
    categorie: 'Finance',
    objectif: "Tenir une comptabilité conforme au référentiel SYCEBNL : plan de comptes, journaux, écritures et états financiers.",
    utilisateurs: ['Comptable', 'Directeur financier', 'Auditeur (lecture)'],
    prerequis: [
      'Exercice comptable ouvert',
      'Plan comptable initialisé',
      'Journaux créés (achats, ventes, banque, caisse, opérations diverses)',
    ],
    procedure: [
      { titre: 'Vérifier le plan comptable', detail: 'Contrôlez la présence des comptes utilisés par votre organisation avant la première saisie.', chemin: 'Comptabilité › Plan comptable' },
      { titre: 'Créer une écriture', detail: 'Sélectionnez le journal et la date, puis saisissez les lignes de débit et de crédit.', chemin: 'Comptabilité › Écritures › Nouvelle écriture' },
      { titre: "Équilibrer l'écriture", detail: "Le total débit doit égaler le total crédit ; l'enregistrement est refusé sinon." },
      { titre: 'Imputer les axes analytiques', detail: 'Projet et bailleur permettent le suivi des fonds affectés.' },
      { titre: 'Consulter grand livre et balance', detail: 'Filtrez par compte, journal ou période pour contrôler les soldes.' },
      { titre: 'Produire les états financiers', detail: 'Les états sont générés à partir des écritures validées de la période.' },
    ],
    erreurs: [
      { probleme: "Écriture refusée à l'enregistrement", cause: 'Déséquilibre débit/crédit ou compte inexistant', solution: 'Corrigez les montants ou créez le compte manquant.' },
      { probleme: 'Écriture hors période', cause: 'Date en dehors de l\'exercice ouvert', solution: "Corrigez la date ou ouvrez l'exercice concerné." },
      { probleme: 'Fonds affectés non suivis', cause: 'Axe projet non renseigné', solution: "Renseignez le projet sur les lignes concernées." },
    ],
    conseils: [
      "Saisissez au fil de l'eau : la reprise de plusieurs mois d'un coup multiplie les erreurs.",
      'Rapprochez la banque chaque mois avant de produire un état.',
      "N'utilisez le journal d'opérations diverses que pour les régularisations.",
    ],
    permissions: ['Rôle Comptable pour la saisie', 'Rôle Directeur financier pour la validation', 'Lecture seule pour les auditeurs'],
  },
  {
    id: 'budget',
    titre: 'Budget',
    href: '/budget',
    categorie: 'Finance',
    objectif: 'Construire les budgets annuels et par projet, puis suivre les écarts.',
    utilisateurs: ['Directeur financier', 'Chargé de projets'],
    prerequis: ['Exercice ouvert', 'Projets créés pour les budgets par projet'],
    procedure: [
      { titre: 'Créer le budget', detail: 'Choisissez le périmètre : organisation ou projet, et la période.', chemin: 'Budget › Nouveau' },
      { titre: 'Saisir les lignes budgétaires', detail: 'Chaque ligne porte un libellé, un compte et un montant prévu.' },
      { titre: 'Valider le budget', detail: 'Un budget validé sert de référence au calcul des écarts.' },
      { titre: 'Suivre la réalisation', detail: 'Le réalisé provient des écritures comptables imputées sur la période.' },
      { titre: 'Analyser les écarts', detail: "Le suivi met en évidence les lignes sur-consommées ou sous-consommées." },
    ],
    erreurs: [
      { probleme: 'Réalisé vide', cause: 'Comptes budgétaires différents des comptes mouvementés', solution: 'Alignez les comptes du budget sur ceux utilisés en saisie.' },
      { probleme: 'Écart aberrant', cause: 'Période budgétaire différente de la période analysée', solution: 'Vérifiez les dates de début et de fin du budget.' },
    ],
    conseils: [
      'Un budget par convention bailleur facilite les rapports financiers exigés.',
      'Révisez le budget en cours d\'exercice via une version révisée plutôt qu\'en écrasant l\'initial.',
    ],
    permissions: ['Écriture Budget', 'Lecture Comptabilité'],
  },
  {
    id: 'tresorerie',
    titre: 'Trésorerie',
    href: '/tresorerie',
    categorie: 'Finance',
    objectif: 'Suivre les comptes bancaires et caisses, les mouvements et les soldes.',
    utilisateurs: ['Comptable', 'Caissier', 'Directeur financier'],
    prerequis: ['Comptes de trésorerie créés avec leur solde d\'ouverture'],
    procedure: [
      { titre: 'Créer les comptes', detail: 'Banque, caisse, mobile money : chaque compte a un intitulé et une devise.', chemin: 'Trésorerie › Comptes' },
      { titre: 'Enregistrer les mouvements', detail: 'Encaissements et décaissements avec date, montant, libellé et pièce.' },
      { titre: 'Effectuer un rapprochement', detail: 'Comparez les mouvements enregistrés au relevé bancaire de la période.' },
      { titre: 'Suivre les soldes', detail: 'Les soldes par compte et la position globale sont affichés en tête de module.' },
    ],
    erreurs: [
      { probleme: 'Solde différent du relevé', cause: 'Mouvements manquants ou saisis deux fois', solution: 'Rapprochez ligne à ligne et corrigez les écarts identifiés.' },
      { probleme: 'Caisse négative', cause: 'Décaissement antérieur à l\'encaissement correspondant', solution: 'Corrigez les dates de valeur des mouvements.' },
    ],
    conseils: ['Rapprochez au moins une fois par mois ; un rapprochement tardif rend la correction coûteuse.'],
    permissions: ['Écriture Trésorerie', 'Validation réservée au responsable financier'],
  },
  {
    id: 'paiements',
    titre: 'Paiements mobiles',
    href: '/paiements',
    categorie: 'Finance',
    objectif: 'Suivre les encaissements et décaissements par mobile money et les rapprocher de la trésorerie.',
    utilisateurs: ['Comptable', 'Caissier'],
    prerequis: ['Compte de trésorerie dédié au mobile money', 'Numéros de téléphone renseignés sur les fiches'],
    procedure: [
      { titre: 'Consulter les transactions', detail: 'La liste présente le sens, le montant, la contrepartie et le statut.', chemin: 'Paiements Mobile' },
      { titre: 'Rapprocher une transaction', detail: 'Associez la transaction au membre, donateur ou fournisseur concerné.' },
      { titre: 'Comptabiliser', detail: "Une fois rapprochée, la transaction alimente le compte de trésorerie correspondant." },
    ],
    erreurs: [
      { probleme: 'Transaction non rattachée', cause: 'Numéro émetteur inconnu du système', solution: 'Complétez le numéro sur la fiche puis relancez le rapprochement.' },
      { probleme: 'Doublon avec une saisie manuelle', cause: 'Mouvement déjà enregistré en trésorerie', solution: 'Supprimez la saisie manuelle et conservez la transaction rapprochée.' },
    ],
    conseils: ['Contrôlez quotidiennement les transactions non rapprochées : leur volume croît vite.'],
    permissions: ['Écriture Trésorerie/Paiements'],
  },
  {
    id: 'achats',
    titre: 'Achats & fournisseurs',
    href: '/achats',
    categorie: 'Finance',
    objectif: "Encadrer la dépense : demande, commande, réception et facture fournisseur.",
    utilisateurs: ['Responsable logistique', 'Comptable', 'Direction'],
    prerequis: ['Fournisseurs créés', 'Budget disponible sur la ligne concernée'],
    procedure: [
      { titre: 'Créer le fournisseur', detail: 'Raison sociale, contacts, coordonnées de règlement.', chemin: 'Achats › Fournisseurs' },
      { titre: 'Émettre une commande', detail: 'Articles, quantités, prix unitaires et imputation projet.' },
      { titre: 'Réceptionner', detail: 'La réception met à jour les stocks pour les articles stockés.' },
      { titre: 'Enregistrer la facture', detail: 'La facture est rapprochée de la commande et de la réception.' },
      { titre: 'Payer', detail: 'Le règlement génère le mouvement de trésorerie correspondant.' },
    ],
    erreurs: [
      { probleme: 'Facture supérieure à la commande', cause: 'Écart de prix ou de quantité', solution: "Justifiez l'écart ou faites corriger la facture avant validation." },
      { probleme: 'Stock non mis à jour', cause: 'Réception non enregistrée', solution: 'Saisissez la réception avant la facture.' },
    ],
    conseils: ["Respectez l'ordre commande → réception → facture : il conditionne la traçabilité pour les audits."],
    permissions: ['Écriture Achats', 'Validation par un profil habilité au-delà d\'un seuil défini'],
  },
  {
    id: 'stocks',
    titre: 'Stocks',
    href: '/stocks',
    categorie: 'Finance',
    objectif: 'Suivre les articles, les entrées/sorties et les niveaux de stock par magasin.',
    utilisateurs: ['Magasinier', 'Logistique'],
    prerequis: ['Articles et magasins créés'],
    procedure: [
      { titre: 'Créer les articles', detail: 'Référence, désignation, unité et seuil d\'alerte.', chemin: 'Stocks › Articles' },
      { titre: 'Enregistrer les entrées', detail: 'Achats réceptionnés ou dons en nature.' },
      { titre: 'Enregistrer les sorties', detail: 'Distribution, consommation interne ou transfert entre magasins.' },
      { titre: 'Réaliser un inventaire', detail: "L'écart entre stock théorique et stock physique est constaté puis régularisé." },
    ],
    erreurs: [
      { probleme: 'Stock négatif', cause: 'Sortie enregistrée avant l\'entrée correspondante', solution: 'Corrigez la chronologie des mouvements.' },
      { probleme: 'Écart d\'inventaire récurrent', cause: 'Sorties non saisies', solution: 'Imposez une saisie au moment de chaque sortie physique.' },
    ],
    conseils: ['Un seuil d\'alerte par article évite les ruptures sur les intrants critiques.'],
    permissions: ['Écriture Stocks'],
  },
  {
    id: 'immobilisations',
    titre: 'Immobilisations',
    href: '/immobilisations',
    categorie: 'Finance',
    objectif: "Recenser les biens durables, leur affectation et leur amortissement.",
    utilisateurs: ['Comptable', 'Logistique'],
    prerequis: ['Comptes d\'immobilisation et d\'amortissement disponibles au plan comptable'],
    procedure: [
      { titre: 'Enregistrer le bien', detail: 'Désignation, date d\'acquisition, valeur, durée d\'amortissement et localisation.', chemin: 'Immobilisations › Nouveau' },
      { titre: 'Affecter le bien', detail: 'Service, projet ou bailleur financeur, utile pour les rapports de fin de convention.' },
      { titre: 'Suivre les amortissements', detail: 'Le plan d\'amortissement découle de la valeur et de la durée saisies.' },
      { titre: 'Sortir un bien', detail: 'Cession, mise au rebut ou transfert, avec date et motif.' },
    ],
    erreurs: [
      { probleme: 'Amortissement non calculé', cause: 'Durée ou date d\'acquisition manquante', solution: 'Complétez la fiche du bien.' },
    ],
    conseils: ['Photographiez et référencez les biens financés par bailleur : certains exigent un inventaire en fin de projet.'],
    permissions: ['Écriture Immobilisations', 'Lecture Comptabilité'],
  },
  {
    id: 'documents',
    titre: 'Documents (GED)',
    href: '/documents',
    categorie: 'Outils',
    objectif: 'Centraliser et retrouver les pièces : contrats, conventions, PV, justificatifs.',
    utilisateurs: ['Tous les profils autorisés'],
    prerequis: ['Arborescence de classement définie'],
    procedure: [
      { titre: 'Téléverser un document', detail: 'Sélectionnez le fichier et renseignez son type et son libellé.', chemin: 'Documents' },
      { titre: 'Classer', detail: 'Rattachez le document à un projet, un membre ou une convention selon le cas.' },
      { titre: 'Rechercher', detail: 'La recherche porte sur le libellé et les métadonnées saisies.' },
      { titre: 'Télécharger ou partager', detail: "L'accès dépend des permissions du profil connecté." },
    ],
    erreurs: [
      { probleme: 'Document introuvable', cause: 'Libellé trop générique ou classement absent', solution: 'Adoptez une convention de nommage : type_entité_date.' },
      { probleme: 'Téléversement refusé', cause: 'Fichier trop volumineux ou format non autorisé', solution: 'Compressez le fichier ou convertissez-le en PDF.' },
    ],
    conseils: ['Nommez les fichiers avant téléversement : renommer après coup est plus long.'],
    permissions: ['Lecture/Écriture Documents selon le rôle'],
  },
  {
    id: 'meal',
    titre: 'MEAL — Suivi & évaluation',
    href: '/meal',
    categorie: 'Outils',
    objectif: 'Définir les indicateurs, collecter les valeurs et mesurer les résultats des projets.',
    utilisateurs: ['Responsable MEAL', 'Chargé de projets'],
    prerequis: ['Projets créés avec leur cadre logique'],
    procedure: [
      { titre: 'Créer les indicateurs', detail: 'Libellé, unité, valeur de référence et cible.', chemin: 'MEAL › Indicateurs' },
      { titre: 'Planifier la collecte', detail: 'Fréquence de mesure et responsable de la donnée.' },
      { titre: 'Saisir les valeurs', detail: 'Chaque relevé est daté et rattaché à la période concernée.' },
      { titre: 'Analyser', detail: 'Le taux d\'atteinte compare la valeur relevée à la cible.' },
    ],
    erreurs: [
      { probleme: 'Taux d\'atteinte supérieur à 100 %', cause: 'Valeurs cumulées saisies comme périodiques', solution: 'Choisissez explicitement un mode cumulé ou périodique et restez cohérent.' },
      { probleme: 'Indicateur sans valeur', cause: 'Collecte non réalisée', solution: 'Assignez un responsable et une échéance de collecte.' },
    ],
    conseils: ['Un indicateur sans source de vérification documentée sera contesté en évaluation externe.'],
    permissions: ['Écriture MEAL', 'Lecture Projets'],
  },
  {
    id: 'reporting',
    titre: 'Rapports & BI',
    href: '/reporting',
    categorie: 'Outils',
    objectif: 'Produire les tableaux de bord et rapports consolidés à partir des données saisies.',
    utilisateurs: ['Direction', 'Directeur financier', 'MEAL'],
    prerequis: ['Données saisies et à jour dans les modules sources'],
    procedure: [
      { titre: 'Choisir le rapport', detail: 'Rapports financiers, activité, projets ou membres.', chemin: 'Rapports & BI' },
      { titre: 'Filtrer', detail: 'Période, projet, bailleur ou service selon le rapport.' },
      { titre: 'Analyser', detail: 'Les graphiques et tableaux se recalculent selon les filtres appliqués.' },
      { titre: 'Exporter', detail: 'Export PDF pour diffusion, tableur pour retraitement.' },
    ],
    erreurs: [
      { probleme: 'Rapport vide', cause: 'Filtres trop restrictifs ou période sans données', solution: 'Élargissez la période et réinitialisez les filtres.' },
      { probleme: 'Écart entre deux rapports', cause: 'Périmètres ou dates de référence différents', solution: 'Comparez les filtres appliqués avant de conclure à une anomalie.' },
    ],
    conseils: ["Un rapport ne vaut que ce que valent les saisies : contrôlez d'abord les modules sources."],
    permissions: ['Lecture des modules concernés par le rapport'],
  },
  {
    id: 'import-export',
    titre: 'Import & export de données',
    href: '/import',
    categorie: 'Outils',
    objectif: 'Charger des données en masse et extraire les listes pour un usage externe.',
    utilisateurs: ['Administrateur', 'Responsable de module'],
    prerequis: ['Fichier source nettoyé', 'Modèle de colonnes respecté'],
    procedure: [
      { titre: 'Choisir le type de données', detail: 'Sélectionnez le module cible de l\'import.', chemin: 'Import de données' },
      { titre: 'Préparer le fichier', detail: 'Une ligne par enregistrement, en-têtes conformes au modèle attendu.' },
      { titre: 'Téléverser et contrôler', detail: 'Les lignes en erreur sont signalées avant validation.' },
      { titre: 'Valider l\'import', detail: 'Seules les lignes valides sont créées.' },
      { titre: 'Exporter', detail: "Depuis chaque module, le bouton d'export produit la liste filtrée." },
    ],
    erreurs: [
      { probleme: 'Import rejeté en totalité', cause: 'En-têtes non conformes', solution: 'Repartez du modèle de colonnes attendu sans renommer les en-têtes.' },
      { probleme: 'Dates décalées', cause: 'Format de date ambigu (jour/mois inversés)', solution: 'Utilisez un format explicite AAAA-MM-JJ.' },
      { probleme: 'Doublons créés', cause: 'Import relancé après un succès partiel', solution: 'Ne réimportez que les lignes en erreur.' },
    ],
    conseils: [
      'Testez toujours sur 5 à 10 lignes avant l\'import complet.',
      'Conservez le fichier source importé : il sert de preuve en cas de contrôle.',
    ],
    permissions: ['Rôle Administrateur ou droit d\'import sur le module'],
  },
  {
    id: 'ia',
    titre: 'Assistant SARA',
    href: '/ia',
    categorie: 'Outils',
    objectif: "Obtenir des explications sur l'ERP et de l'aide à la navigation.",
    utilisateurs: ['Tous les utilisateurs'],
    prerequis: ['Être connecté'],
    procedure: [
      { titre: 'Ouvrir l\'assistant', detail: 'Depuis le menu Assistant IA.', chemin: 'Assistant IA' },
      { titre: 'Poser une question', detail: 'Formulez la question en français, en précisant le module concerné.' },
      { titre: 'Suivre les indications', detail: "SARA oriente vers le bon écran ; les actions restent réalisées par l'utilisateur." },
    ],
    erreurs: [
      { probleme: 'Réponse trop générale', cause: 'Question imprécise', solution: 'Indiquez le module, l\'action et le message d\'erreur exact.' },
    ],
    conseils: [
      "Ne communiquez pas d'informations personnelles sensibles dans les échanges.",
      "Pour un incident bloquant, ouvrez un ticket de support plutôt que d'insister avec l'assistant.",
    ],
    permissions: ['Accès Assistant IA'],
  },
  {
    id: 'audit',
    titre: 'Journal d\'audit',
    href: '/audit',
    categorie: 'Administration',
    objectif: 'Consulter la trace des actions réalisées dans le système.',
    utilisateurs: ['Administrateur', 'Auditeur interne'],
    prerequis: ['Droit de consultation du journal'],
    procedure: [
      { titre: 'Ouvrir le journal', detail: 'Les entrées listent l\'auteur, l\'action, l\'objet et l\'horodatage.', chemin: 'Audit' },
      { titre: 'Filtrer', detail: 'Par utilisateur, période ou type d\'action.' },
      { titre: 'Exporter', detail: 'Extraction de la sélection pour une mission de contrôle.' },
    ],
    erreurs: [
      { probleme: 'Action attendue absente du journal', cause: 'Période ou filtre utilisateur inexact', solution: 'Élargissez la période et retirez les filtres.' },
    ],
    conseils: ['Consultez le journal après tout incident de données avant de reconstituer manuellement.'],
    permissions: ['Rôle Administrateur ou Auditeur'],
  },
  {
    id: 'parametres',
    titre: 'Paramètres & administration',
    href: '/parametres',
    categorie: 'Administration',
    objectif: "Configurer l'organisation, les utilisateurs, les rôles et les données de référence.",
    utilisateurs: ['Administrateur'],
    prerequis: ['Rôle Administrateur'],
    procedure: [
      { titre: 'Organisation', detail: 'Identité, logo, coordonnées utilisées sur les documents.', chemin: 'Paramètres › Organisation' },
      { titre: 'Utilisateurs', detail: 'Création, désactivation et réinitialisation d\'accès.', chemin: 'Paramètres › Utilisateurs' },
      { titre: 'Rôles et permissions', detail: 'Chaque rôle regroupe des droits de lecture et d\'écriture par module.' },
      { titre: 'Données de référence', detail: 'Catégories, journaux, types de documents et autres listes partagées.' },
      { titre: 'Sécurité', detail: 'Règles de mot de passe et options de session.' },
    ],
    erreurs: [
      { probleme: 'Utilisateur sans accès après création', cause: 'Aucun rôle attribué', solution: 'Attribuez un rôle puis demandez une reconnexion.' },
      { probleme: 'Modification de paramètre sans effet', cause: 'Session en cours avec anciennes valeurs', solution: 'Déconnectez-vous puis reconnectez-vous.' },
    ],
    conseils: [
      'Appliquez le principe du moindre privilège : un rôle large est un risque.',
      'Désactivez les comptes des personnes parties plutôt que de les partager.',
    ],
    permissions: ['Rôle Administrateur exclusivement'],
  },
];

export const CATEGORIES_GUIDE = [
  'Démarrage',
  'Relations',
  'Activités',
  'Finance',
  'Outils',
  'Administration',
] as const;
